# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#  movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#  Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
Business.destroy_all
Review.destroy_all


demo = User.create(first_name: 'Demo', last_name: 'User', email: 'noemail@email.com', password: 'password', zip_code: '94018')
user1 = User.create(first_name: 'Mary', last_name: 'Poppins', email: 'mary123@mail.com', password: 'password', zip_code: '94012')
user2 = User.create(first_name: 'Mike', last_name: 'Smith', email: 'mikesmith@mail.com', password: 'password', zip_code: '94016')
user3 = User.create(first_name: 'Jessica', last_name: 'Jones', email: 'jessicaaaaaa@mail.com', password: 'password', zip_code: '94013')
user4 = User.create(first_name: 'Serena', last_name: 'Williams', email: 'ilovetennis@mail.com', password: 'password', zip_code: '94014')
user5 = User.create(first_name: 'Joe', last_name: 'Bruin', email: 'bearbearbear@mail.com', password: 'password', zip_code: '90024')
user6 = User.create(first_name: 'Matt', last_name: 'Miller', email: 'mercerindisguise@mail.com', password: 'password', zip_code: '90210')
user7 = User.create(first_name: 'Finn', last_name: 'Human', email: 'jakethedog@mail.com', password: 'password', zip_code: '94015')
user8 = User.create(first_name: 'Wilson', last_name: 'Coconut', email: 'imlost@mail.com', password: 'password', zip_code: '94019')
user9 = User.create(first_name: 'Sandy', last_name: 'Star', email: 'bobthesponge@mail.com', password: 'password', zip_code: '94017')
user10 = User.create(first_name: 'Elaine', last_name: 'Wong', email: 'tofurkey@mail.com', password: 'password', zip_code: '91001')
user11 = User.create(first_name: 'Albert', last_name: 'Coulson', email: 'pianoman@mail.com', password: 'password', zip_code: '94133')
user12 = User.create(first_name: 'Lily', last_name: 'Janeway', email: 'flowersaregreat@mail.com', password: 'password', zip_code: '94105')
user13 = User.create(first_name: 'Jackie', last_name: 'Jung', email: 'idokungfu@mail.com', password: 'password', zip_code: '94019')
user14 = User.create(first_name: 'Ryan', last_name: 'Chan', email: 'eateateatme@mail.com', password: 'password', zip_code: '94012')
user15 = User.create(first_name: 'Elizabeth', last_name: 'Bennett', email: 'bookgal13@mail.com', password: 'password', zip_code: '94011')
user16 = User.create(first_name: 'Ben', last_name: 'Stiller', email: 'moviesallday@mail.com', password: 'password', zip_code: '90024')
user17 = User.create(first_name: 'Logan', last_name: 'Clarke', email: 'supesnotsuits@mail.com', password: 'password', zip_code: '90025')
user18 = User.create(first_name: 'Adam', last_name: 'Anderson', email: 'mranderson@mail.com', password: 'password', zip_code: '91733')
user19 = User.create(first_name: 'Michelle', last_name: 'Warren', email: 'bestseatsinthehouse@mail.com', password: 'password', zip_code: '91732')
user20 = User.create(first_name: 'Jake', last_name: 'Carter', email: 'someguy11@mail.com', password: 'password', zip_code: '91731')
user21 = User.create(first_name: 'Thomas', last_name: 'Ward', email: 'yoursmileiscute@mail.com', password: 'password', zip_code: '94012')
user22 = User.create(first_name: 'Catherine', last_name: 'Simmons', email: 'persimmon@mail.com', password: 'password', zip_code: '90211')
user23 = User.create(first_name: 'Hannah', last_name: 'Foster', email: 'fosterlove@mail.com', password: 'password', zip_code: '90024')
user24 = User.create(first_name: 'Sofia', last_name: 'Perez', email: 'sofiathegreat@mail.com', password: 'password', zip_code: '94133')
user25 = User.create(first_name: 'Quyen', last_name: 'Tran', email: 'qtpie@mail.com', password: 'password', zip_code: '94132')

demo.photo.attach(io: File.open('./app/assets/images/user/demo.png'), filename: 'demo.png')
user1.photo.attach(io: File.open('./app/assets/images/user/user1.jpg'), filename: 'user1.jpg')
user2.photo.attach(io: File.open('./app/assets/images/user/user2.jpg'), filename: 'user2.jpg')
user3.photo.attach(io: File.open('./app/assets/images/user/user3.jpg'), filename: 'user3.jpg')
user4.photo.attach(io: File.open('./app/assets/images/user/user4.jpg'), filename: 'user4.jpg')
user5.photo.attach(io: File.open('./app/assets/images/user/user5.jpg'), filename: 'user5.jpg')
user6.photo.attach(io: File.open('./app/assets/images/user/user6.jpg'), filename: 'user6.jpg')
user7.photo.attach(io: File.open('./app/assets/images/user/user7.jpg'), filename: 'user7.jpg')
user8.photo.attach(io: File.open('./app/assets/images/user/user8.jpg'), filename: 'user8.jpg')
user9.photo.attach(io: File.open('./app/assets/images/user/user9.jpg'), filename: 'user9.jpg')
user10.photo.attach(io: File.open('./app/assets/images/user/user10.jpeg'), filename: 'user10.jpeg')
user11.photo.attach(io: File.open('./app/assets/images/user/user11.jpg'), filename: 'user11.jpg')
user12.photo.attach(io: File.open('./app/assets/images/user/user12.jpg'), filename: 'user12.jpg')
user13.photo.attach(io: File.open('./app/assets/images/user/user13.jpg'), filename: 'user13.jpg')
user14.photo.attach(io: File.open('./app/assets/images/user/user14.jpg'), filename: 'user14.jpg')
user15.photo.attach(io: File.open('./app/assets/images/user/user15.jpg'), filename: 'user15.jpg')
user16.photo.attach(io: File.open('./app/assets/images/user/user16.jpg'), filename: 'user16.jpg')
user17.photo.attach(io: File.open('./app/assets/images/user/user17.jpg'), filename: 'user17.jpg')
user18.photo.attach(io: File.open('./app/assets/images/user/user18.jpg'), filename: 'user18.jpg')
user19.photo.attach(io: File.open('./app/assets/images/user/user19.jpg'), filename: 'user19.jpg')
user20.photo.attach(io: File.open('./app/assets/images/user/user20.png'), filename: 'user20.png')
user21.photo.attach(io: File.open('./app/assets/images/user/user21.jpg'), filename: 'user21.jpg')
user22.photo.attach(io: File.open('./app/assets/images/user/user22.jpg'), filename: 'user22.jpg')
user23.photo.attach(io: File.open('./app/assets/images/user/user23.jpg'), filename: 'user23.jpg')
user24.photo.attach(io: File.open('./app/assets/images/user/user24.jpg'), filename: 'user24.jpg')
user25.photo.attach(io: File.open('./app/assets/images/user/user25.jpg'), filename: 'user25.jpg')

business1 = Business.create(business_name: "Fog Harbor Fish House", address: "Pier 39 Ste A-202", city: "San Francisco", state: "CA", zip_code: "94133", latitude: 37.80964, longitude: -122.41025, phone: "(415) 421-2442", website: "fogharbor.com", price: '$$')
business2 = Business.create(business_name: "Marufuku Ramen", address: "1581 Webster St", city: "San Francisco", state: "CA", zip_code: "94115", latitude: 37.78537, longitude: -122.43146, phone: "(415) 872-9786", website: "marufukuramen.com", price: '$$')
business3 = Business.create(business_name: "The House", address: "1230 Grant Ave", city: "San Francisco", state: "CA", zip_code: "94133", latitude: 37.797952, longitude: -122.407148, phone: "(415) 986-8612", website: "thehse.com", price: '$$$')
business4 = Business.create(business_name: "Sotto Mare Oysteria and Seafood", address: "552 Green St", city: "San Francisco", state: "CA", zip_code: "94133", latitude: 37.799670, longitude: -122.408290, phone: "(415) 398-3181", website: "sottomaresf.com", price: '$$')
business5 = Business.create(business_name: "Liholiho Yacht Club", address: "871 Sutter St", city: "San Francisco", state: "CA", zip_code: "94109", latitude: 37.788180, longitude: -122.414580, phone: "(415) 440-5446", website: "lycsf.com", price: '$$$')
business6 = Business.create(business_name: "Tacorea", address: "809 Bush St", city: "San Francisco", state: "CA", zip_code: "94108", latitude: 37.785570, longitude: -122.445020, phone: "(415) 885-1325", website: "tacorea.com", price: '$')
business7 = Business.create(business_name: "Trattoria Contadina", address: "1800 Mason St", city: "San Francisco", state: "CA", zip_code: "94133", latitude: 37.800180, longitude: -122.412280, phone: "(415) 982-5728", website: "trattoriacontadina.com", price: '$$')
business8 = Business.create(business_name: "Crispy Tacos", address: "1500 Broadway", city: "San Francisco", state: "CA", zip_code: "94109", latitude: 37.796050, longitude: -122.422110, phone: "(415) 409-8226", website: "nickscrispytacos.com", price: '$')
business9 = Business.create(business_name: "Scoma Restaurant", address: "1965 Al Scoma Way", city: "San Francisco", state: "CA", zip_code: "94133", latitude: 37.809030, longitude: -122.418020, phone: "(415) 771-4383", website: "scomas.com", price: '$$$')
business10 = Business.create(business_name: "The Boardroom", address: "1600 Powell St", city: "San Francisco", state: "CA", zip_code: "94133", latitude: 37.799470, longitude: -122.410430, phone: "(415) 982-8898", website: "boardroomsf.com", price: '$')

# business11 = Business.create(business_name: "Del Popolo", address: "855 Bush St", city: "San Francisco", state: "CA", zip_code: "94108", latitude: 37.789551, longitude: -122.411331, phone: "(415) 589-7940", website: "delpopolosf.com", price: '$$')
# business12 = Business.create(business_name: "Uncle Vito's", address: "700 Bush St", city: "San Francisco", state: "CA", zip_code: "94108", latitude: 37.7903112, longitude: -122.4089665, phone: "(415) 391-5008", website: "unclevitos.com", price: '$$')


business1.photo.attach(io: File.open('./app/assets/images/business/1-fog/fog1.jpg'), filename: 'fog1-1.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog1.jpg'), filename: 'fog1.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog2.jpg'), filename: 'fog2.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog3.jpg'), filename: 'fog3.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog4.jpg'), filename: 'fog4.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog5.jpg'), filename: 'fog5.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog6.jpg'), filename: 'fog6.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog7.jpg'), filename: 'fog7.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog8.jpg'), filename: 'fog8.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog9.jpg'), filename: 'fog9.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog10.jpg'), filename: 'fog10.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog11.jpg'), filename: 'fog11.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog12.jpg'), filename: 'fog12.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog13.jpg'), filename: 'fog13.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog14.jpg'), filename: 'fog14.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog15.jpg'), filename: 'fog15.jpg')

business2.photo.attach(io: File.open('./app/assets/images/business/2-maru/maru1.jpg'), filename: 'maru1-1.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru1.jpg'), filename: 'maru1.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru2.jpg'), filename: 'maru2.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru3.jpg'), filename: 'maru3.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru4.jpg'), filename: 'maru4.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru5.jpg'), filename: 'maru5.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru6.jpg'), filename: 'maru6.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru7.jpg'), filename: 'maru7.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru8.jpg'), filename: 'maru8.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru9.jpg'), filename: 'maru9.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru10.jpg'), filename: 'maru10.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru11.jpg'), filename: 'maru11.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru12.jpg'), filename: 'maru12.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru13.jpg'), filename: 'maru13.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru14.jpg'), filename: 'maru14.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru15.jpg'), filename: 'maru15.jpg')

business3.photo.attach(io: File.open('./app/assets/images/business/3-house/house1.jpg'), filename: 'house1-1.jpg')
business3.pics.attach(io: File.open('./app/assets/images/business/3-house/house1.jpg'), filename: 'house1.jpg')
business3.pics.attach(io: File.open('./app/assets/images/business/3-house/house2.jpg'), filename: 'house2.jpg')
business3.pics.attach(io: File.open('./app/assets/images/business/3-house/house3.jpg'), filename: 'house3.jpg')
business3.pics.attach(io: File.open('./app/assets/images/business/3-house/house4.jpg'), filename: 'house4.jpg')
business3.pics.attach(io: File.open('./app/assets/images/business/3-house/house5.jpg'), filename: 'house5.jpg')
business3.pics.attach(io: File.open('./app/assets/images/business/3-house/house6.jpg'), filename: 'house6.jpg')
business3.pics.attach(io: File.open('./app/assets/images/business/3-house/house7.jpg'), filename: 'house7.jpg')
business3.pics.attach(io: File.open('./app/assets/images/business/3-house/house8.jpg'), filename: 'house8.jpg')
business3.pics.attach(io: File.open('./app/assets/images/business/3-house/house9.jpg'), filename: 'house9.jpg')
business3.pics.attach(io: File.open('./app/assets/images/business/3-house/house10.jpg'), filename: 'house10.jpg')
business3.pics.attach(io: File.open('./app/assets/images/business/3-house/house11.jpg'), filename: 'house11.jpg')
business3.pics.attach(io: File.open('./app/assets/images/business/3-house/house12.jpg'), filename: 'house12.jpg')
business3.pics.attach(io: File.open('./app/assets/images/business/3-house/house13.jpg'), filename: 'house13.jpg')

business4.photo.attach(io: File.open('./app/assets/images/business/4-sotto/sotto1.jpg'), filename: 'sotto1-1.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto1.jpg'), filename: 'sotto1.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto2.jpg'), filename: 'sotto2.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto3.jpg'), filename: 'sotto3.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto4.jpg'), filename: 'sotto4.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto5.jpg'), filename: 'sotto5.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto6.jpg'), filename: 'sotto6.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto7.jpg'), filename: 'sotto7.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto8.jpg'), filename: 'sotto8.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto9.jpg'), filename: 'sotto9.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto10.jpg'), filename: 'sotto10.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto11.jpg'), filename: 'sotto11.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto12.jpg'), filename: 'sotto12.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto13.jpg'), filename: 'sotto13.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto14.jpg'), filename: 'sotto14.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto15.jpg'), filename: 'sotto15.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto16.jpg'), filename: 'sotto16.jpg')

business5.photo.attach(io: File.open('./app/assets/images/business/5-liho/liho1.jpg'), filename: 'liho1-1.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho1.jpg'), filename: 'liho1.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho2.jpg'), filename: 'liho2.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho3.jpg'), filename: 'liho3.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho4.jpg'), filename: 'liho4.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho5.jpg'), filename: 'liho5.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho6.jpg'), filename: 'liho6.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho7.jpg'), filename: 'liho7.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho8.jpg'), filename: 'liho8.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho9.jpg'), filename: 'liho9.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho10.jpg'), filename: 'liho10.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho11.jpg'), filename: 'liho11.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho12.jpg'), filename: 'liho12.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho13.jpg'), filename: 'liho13.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho14.jpg'), filename: 'liho14.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho15.jpg'), filename: 'liho15.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho16.jpg'), filename: 'liho16.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho17.jpg'), filename: 'liho17.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho18.jpg'), filename: 'liho18.jpg')

business6.photo.attach(io: File.open('./app/assets/images/business/6-taco/taco1.jpg'), filename: 'taco1-1.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco1.jpg'), filename: 'taco1.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco2.jpg'), filename: 'taco2.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco3.jpg'), filename: 'taco3.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco4.jpg'), filename: 'taco4.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco5.jpg'), filename: 'taco5.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco6.jpg'), filename: 'taco6.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco7.jpg'), filename: 'taco7.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco8.jpg'), filename: 'taco8.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco9.jpg'), filename: 'taco9.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco10.jpg'), filename: 'taco10.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco11.jpg'), filename: 'taco11.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco12.jpg'), filename: 'taco12.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco13.jpg'), filename: 'taco13.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco14.jpg'), filename: 'taco14.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco15.jpg'), filename: 'taco15.jpg')

business7.photo.attach(io: File.open('./app/assets/images/business/7-tratt/tratt1.jpg'), filename: 'tratt1-1.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt1.jpg'), filename: 'tratt1.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt2.jpg'), filename: 'tratt2.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt3.jpg'), filename: 'tratt3.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt4.jpg'), filename: 'tratt4.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt5.jpg'), filename: 'tratt5.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt6.jpg'), filename: 'tratt6.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt7.jpg'), filename: 'tratt7.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt8.jpg'), filename: 'tratt8.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt9.jpg'), filename: 'tratt9.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt10.jpg'), filename: 'tratt10.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt11.jpg'), filename: 'tratt11.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt12.jpg'), filename: 'tratt12.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt13.jpg'), filename: 'tratt13.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt14.jpg'), filename: 'tratt14.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt15.jpg'), filename: 'tratt15.jpg')

business8.photo.attach(io: File.open('./app/assets/images/business/8-crisp/crisp1.jpg'), filename: 'crisp1-1.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp1.jpg'), filename: 'crisp1.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp2.jpg'), filename: 'crisp2.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp3.jpg'), filename: 'crisp3.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp4.jpg'), filename: 'crisp4.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp5.jpg'), filename: 'crisp5.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp6.jpg'), filename: 'crisp6.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp7.jpg'), filename: 'crisp7.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp8.jpg'), filename: 'crisp8.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp9.jpg'), filename: 'crisp9.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp10.jpg'), filename: 'crisp10.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp11.jpg'), filename: 'crisp11.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp12.jpg'), filename: 'crisp12.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp13.jpg'), filename: 'crisp13.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp14.jpg'), filename: 'crisp14.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp15.jpg'), filename: 'crisp15.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp16.jpg'), filename: 'crisp16.jpg')

business9.photo.attach(io: File.open('./app/assets/images/business/9-scoma/scoma1.jpg'), filename: 'scoma1-1.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma1.jpg'), filename: 'scoma1.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma2.jpg'), filename: 'scoma2.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma3.jpg'), filename: 'scoma3.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma4.jpg'), filename: 'scoma4.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma5.jpg'), filename: 'scoma5.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma6.jpg'), filename: 'scoma6.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma7.jpg'), filename: 'scoma7.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma8.jpg'), filename: 'scoma8.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma9.jpg'), filename: 'scoma9.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma10.jpg'), filename: 'scoma10.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma11.jpg'), filename: 'scoma11.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma12.jpg'), filename: 'scoma12.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma13.jpg'), filename: 'scoma13.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma14.jpg'), filename: 'scoma14.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma15.jpg'), filename: 'scoma15.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma16.jpg'), filename: 'scoma16.jpg')

business10.photo.attach(io: File.open('./app/assets/images/business/10-board/board1.jpg'), filename: 'board1-1.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board1.jpg'), filename: 'board1.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board2.jpg'), filename: 'board2.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board3.jpg'), filename: 'board3.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board4.jpg'), filename: 'board4.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board5.jpg'), filename: 'board5.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board6.jpg'), filename: 'board6.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board7.jpg'), filename: 'board7.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board8.jpg'), filename: 'board8.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board9.jpg'), filename: 'board9.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board10.jpg'), filename: 'board10.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board11.jpg'), filename: 'board11.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board12.jpg'), filename: 'board12.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board13.jpg'), filename: 'board13.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board14.jpg'), filename: 'board14.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board15.jpg'), filename: 'board15.jpg')


Review.create(business_id: business1.id, user_id: user1.id, rating: 5, body: "Had the best dinner here!! It is right off the pier with great views of the city, the bay, and most importantly, the Golden Gate Bridge! Make sure to get reservations and ask for a seat by the window to get a great sunset view at dinner.")
Review.create(business_id: business1.id, user_id: user2.id, rating: 5, body: "I ate here yesterday as my first meal ever in San Francisco and I was definitely not disappointed! I came at happy hour time (around 4pm) and so I got to take part of some happy hour specials while sitting at the bar. I came here for the sourdough bread bowl of clam chowder, and probably would've been fine with just that - but I couldn't pass up the fried lemon calamari on the happy hour menu for $7, and was very happy that I got that as well! (And some wine, of course).")
Review.create(business_id: business1.id, user_id: user6.id, rating: 3, body: "Came here for dinner last night. Its right on pier 39 overlooking the marina. Seevice was good. Our waitress was nice and attentive. Ambience was inviting. Food though was sub par, especially for the price.")
Review.create(business_id: business1.id, user_id: user9.id, rating: 4, body: "Seafood party! Love that you get on the wait list via Berp and avoid waiting around uncessarily. The clam chowder here was so amazing! It was creamy with pieces of clams and potato and I wanted to lick the bowl. Scallop, crab, and clam risotto was pretty tasty at first bite, but once I had a bite of the seafood penne pasta, it was like move over risotto. Red sauce is better than white sauce BTW.")
Review.create(business_id: business1.id, user_id: user12.id, rating: 4, body: "We made a reservation in advance, so we got the chance to sit by the window. The service was really attentive. We were taken good care of by the waiter all night. Recommended for dating and friends gathering. It is a touristy spot but it won't disappoint.")
Review.create(business_id: business1.id, user_id: user18.id, rating: 3, body: "Stopped in here for some chowder, and literally that was the only thing, although we ended up trying the oysters, too, which were small and not really that good (dry and sticky). Next time will have to ask to see what they have as the half dozen was not worth it. Front had plenty of seats though we still waited for a table.")
Review.create(business_id: business1.id, user_id: user19.id, rating: 5, body: "Outstanding service and great food... My wife and I came to SF for our anniversary and we wanted to try a good selection of the crab places. This restaurant was by far the best! We came back twice especially after our actual anniversary evening dinner was a complete bust at another restaurant.")

Review.create(business_id: business2.id, user_id: user4.id, rating: 5, body: "We went to the place because of the reviews on Berp. There was a big line and we had to wait for a while, but it was completely worth it! Ramen was so spicy and so so good.")
Review.create(business_id: business2.id, user_id: user5.id, rating: 4, body: "Best ramen in SF. The wait is long. We went for lunch and got on the waitlist, but still had to wait around 45 min. Broth was amazing and the egg was cooked perfectly. Definitely recommend this place.")
Review.create(business_id: business2.id, user_id: user6.id, rating: 2, body: "This is the saltiest Ramen we've ever had. My tongue still hurts. Got the special DX sizzling chicken. Chicken was hard and dry. Not sure if it was an off day, but none of the people in my group liked their food.")
Review.create(business_id: business2.id, user_id: user7.id, rating: 5, body: "Definitely the best ramen place I've been to in a long time i would have gotten the pork belly bun small bites (MarufukuBites) but was in a rush to go see a movie. It is located on the second floor of the far western building of Japantown near the theaters.")
Review.create(business_id: business2.id, user_id: user10.id, rating: 4, body: "Was the ramen really good? Yeah. Was it the best ramen I've had in SF? Probably. Was it the best in the Bay Area? Meh. I think there are definitely better ramen spots if you travel outside of SF. Marufuku just makes a solid bowl of ramen, which is pretty much standard fare for anywhere in Japan. There wasn't anything particularly special about it that makes me want to come back and battle the wait time again.")
Review.create(business_id: business2.id, user_id: user11.id, rating: 4, body: "Came here on a Sunday around opening time in hopes of not having to wait for very long, but still ended up having to put my name on a waitlist. Fortunately, we didn't have to wait too long and were seated within 30 mins. Overall, a good bowl of ramen! Would definitely be worth the wait (if the wait isn't too long).")

Review.create(business_id: business3.id, user_id: user1.id, rating: 5, body: "I love this place, and more than being happy, I have an inner sense of peace and joy as I imbibe the whole dining experience. No other restaurant makes me this happy. I hope The House stays this consistent and high quality for years to come.")
Review.create(business_id: business3.id, user_id: user11.id, rating: 5, body: "A perfect date spot for a potential significant other or someone that you've been with for a while, or just a friend. You won't be disappointed with the food that you order here!")
Review.create(business_id: business3.id, user_id: user21.id, rating: 5, body: "Make sure to make a reservation in advance. Place is small inside and gets super packed! Their food!!!! SOOOO GOOD!!! Ordered salmon fried rolls.")
Review.create(business_id: business3.id, user_id: user2.id, rating: 5, body: "We made a reservation (and I highly recommend you do the same, this place is super small and always packed). It was 6 of us at the table and we decided to order a bunch of different things off of their menu and just share it all. I am so glad we did that because everything was so delicious, flavorful and cooked to perfection. We were so excited about our meals, I totally forgot to take photos except for one! We loved our food and I know you will too! This place is a must try!")
Review.create(business_id: business3.id, user_id: user12.id, rating: 5, body: "The House is just exceptional! To be honest, I wasn't expecting much from this place because I assumed it would be a mish mash of glorified asian fusion but it blew me away! I'd definitely come back (either come really early or come with a reservation which can be hard to come by). This is a special occasion meal!")
Review.create(business_id: business3.id, user_id: user22.id, rating: 5, body: "Came by for dinner the other night and the experience was phenomenal as always! Reservations were available via Berp and we were seated upon arrival! The Black Cod was very fresh and perfectly cooked. The avocado roll complemented the dish perfectly!")
Review.create(business_id: business3.id, user_id: user24.id, rating: 5, body: "The House is damn good! With the reviews this restaurant has, I came in with high expectations and they were still exceeded. Definitely worthy of a visit. The restaurant is small, but the food is excellent. I have to say it was the best Asian fusion food I have had in SF. Dishes that stood out were the wasabi noodles with flatiron steak, a Korean short rib special, octopus, deep fried salman roll, and a scallop special. All were excellent!")
Review.create(business_id: business3.id, user_id: user25.id, rating: 5, body: "We were walking around North Beach and decided to check on Berp for a good place for lunch. The House popped up with 5 stars so we walked right over. It was past the usual lunch hour rush so we were seated within a minute of arriving.")

Review.create(business_id: business4.id, user_id: user3.id, rating: 5, body: "Great food great atmosphere! Went there on a week day night and it was packed. The restaurant is very small. But the food were so delicious! Absolutely loved it. One thing I did not like was their salad... it was disappointing. Looked like the stuff you put underneath tonkatsu lol But will definitely come back!")
Review.create(business_id: business4.id, user_id: user14.id, rating: 4, body: "Monday night at arrived at seven thirty waited about thirty minutes. The best cioppino? No. I think what makes it best is that they don't skimp out on the seafood and big portion. As for flavor? Nothing special. Me and my bf thought it was bland. As for the crab diavolo with linguine omggggg so freaking good. All the flavors were definitely there! Yummmmmy! I finished everything and I only got the half portion but it was good enough.")
Review.create(business_id: business4.id, user_id: user15.id, rating: 5, body: "This was our must-visit restaurant during our Cal trip. I was definitely looking forward to trying The Best Damn Cioppino since my friend kept raving about it! I must admit that it is probably the best cioppino I've ever had - and I'm from Seattle! We ordered some tasty oysters too! Sotto Mare is definitely an old-school San Francisco restaurant, which is awesome! Definitely stop in if you find yourself in North Beach!")
Review.create(business_id: business4.id, user_id: user16.id, rating: 5, body: "You really get that authentic Italian vibe once you step into the place. The smell of fresh seafood and freshly cooked pasta are just amazing. Definitely my favorite Italian restaurant in SF, so far. The restaurant is super crowded during the weekend and there is usually a long line so make sure to book beforehand. ")
Review.create(business_id: business4.id, user_id: user17.id, rating: 4, body: "Of course, we got the famous cioppino, which definitely lived up to the hype: tasty fresh seafood stewed in a nicely seasoned savory tomato broth with a sensibly portioned (read: they're not trying to rip you off by loading up on the cheap carbs) amount of al-dente pasta. Make sure to save some of the bread that they give you at the beginning of the meal in order to soak up that wonderful broth.")
Review.create(business_id: business4.id, user_id: user18.id, rating: 1, body: "I have absolutely NO idea what these 3300 reviewers see in this place. Coming from San Diego, I've had my share of seafood, and this place is comparable to Olive Garden at best. The bread was hard and cold. The oyster shooter, talk about an overstatement. Overall, as Ariana Grande would say: thank you, next.")
Review.create(business_id: business4.id, user_id: user19.id, rating: 5, body: "This is hands down one of the best restaurants I've ever eaten at. I was introduced to it a few years ago by one of my best friends and I've been coming back ever since. Have absolutely zero complaints about this place, come here immediately!")
Review.create(business_id: business4.id, user_id: user23.id, rating: 5, body: "BEST SEAFOOD IVE EVER HAD. The cioppino was INCREDIBLE and definitely big enough to share between 2-4 people. Would highly recommend. We were too late to get oysters but I plan on going back. The wait if you don't have a reservation can be long. We waited 2 hours, but it was WELL WORTH IT. incredible.")

Review.create(business_id: business5.id, user_id: user6.id, rating: 4, body: "Really enjoyed dinner at Liholiho. There were some dishes that weren't my favorite, but the others made up for it. We ordered way too much and had lots to take home, but was happy we got to try so many dishes. Highlights were the beef tongue buns and curry clams. The squid salad and fried oysters were also very delicious.")
Review.create(business_id: business5.id, user_id: user9.id, rating: 4, body: "Got to try the Housemade spam. It's less saltier than regular spam served on a bed of rice with pickles and furikake. I liked this dish a lot but I wish we had sheets of seaweed to wrap this with the rice. Musubi all day! Would they judge me if I bought in my own seaweed packets? Being that it's less salty I definitely didn't feel guilty for eating it and the pickles added some nice crunch to the dish.")
Review.create(business_id: business5.id, user_id: user12.id, rating: 5, body: "The restaurant scene is very casual and a touch loud! I loved how they brought the concept of an open kitchen to a whole new level with the opportunity to walk through the entire kitchen on the way back to the restaurant!")
Review.create(business_id: business5.id, user_id: user15.id, rating: 5, body: "Managed to walk in sans reservation the night before thanksgiving. The bar staff were incredibly knowledgeable, and the drinks were delicious. I enjoyed every dish we ate - the chicken liver mousse toast was my favourite. Almost gave only 4 stars as the boyfriend didn't enjoy the food, but he can write his own review. :)")
Review.create(business_id: business5.id, user_id: user18.id, rating: 4, body: "Finally get a chance to try this place out with a group of friend. Reservation is highly recommended for big party; It is always challenging to get so often you would have to make reservation 2 months in advance. The benefit of eating with a big group is you get to try many plates. Definitely recommend to others")
Review.create(business_id: business5.id, user_id: user21.id, rating: 3, body: "I've heard more than enough raves and reviews about this place that my expectations were HYPED. UP. But what they say is true - the higher expectations rise, they harder they fall (ish). Not to say that Liholiho was bad or a poor experience, but I found the food just...OK. Our meal turned out to be almost $200 after tax and tip. I'm not one to put a price tag on an experience and a good meal, but I honestly didn't see the worth in it.")
Review.create(business_id: business5.id, user_id: user24.id, rating: 4, body: "Overall, I really enjoyed the meal and the ambiance. The apps are the star here and if I got back, I'll order mainly apps and maybe share an entree. You try it out yourself and make a call but remember 1 month prior at midnight - Be online or you won't get a reasonable time for a dinner reso.")
Review.create(business_id: business5.id, user_id: user3.id, rating: 5, body: "Glad our lovely Elite friend Tracey A. booked the Ohana Table. Talk about a fabulous dining experience with the Yelp family from near & far. Hawaii peeps Terry and Peter were in the house. I've been wanting to try this place, but waited for the madness to die down. I can tell you it hasn't!")

Review.create(business_id: business6.id, user_id: user1.id, rating: 5, body: "A little taco parlor near Union Square and Masonic is our go to place when we are in the neighborhood. The seating is a little cozy and people watchers may enjoy sitting near the window.")
Review.create(business_id: business6.id, user_id: user2.id, rating: 4, body: "What a great place! Probably the best tacos I have had in San Francisco. Very convenient for a late night dinner. Price is very reasonable as well. Very nice overall.")
Review.create(business_id: business6.id, user_id: user3.id, rating: 5, body: "I've always enjoyed their California burrito, which is their version of a combination. It comes with onion, bell peppers, mushrooms and sausage. I like that they don't skimp on their portions their crust has a nice texture to it and they are very reasonably priced when you compare to other taco places in SOMA.")
Review.create(business_id: business6.id, user_id: user4.id, rating: 3, body: "Seeing all the reviews at this place made me want to come and check it out. And to be honest, to me, this place wasn't the most exciting taco place. I have started to become more inclined to eating Neapolitan style of tacos. I think though, this taco was just okay.")
Review.create(business_id: business6.id, user_id: user5.id, rating: 4, body: "Can't go wrong with a bulgogi taco. The California burrito was good, but a tad too much onion. They serve Drake's IPA which was good. Service was ok. The server checked on us a couple of times. Just not the friendliest.")
Review.create(business_id: business6.id, user_id: user6.id, rating: 5, body: "The food is good and the prices are very reasonable for the quality. They offer takeout and delivery too. Keep an eye out for the daily specials!")
Review.create(business_id: business6.id, user_id: user7.id, rating: 1, body: "I decided to get a taco from Tacorea while waiting for my laundry to complete across the road. At around 9:30 pm on Sunday it was slammed. The person taking orders was obviously having a bad day. He was out rightly rude to people who were simply placing orders.")

Review.create(business_id: business7.id, user_id: user8.id, rating: 5, body: "A cosy, Italian restaurant with some classically cooked food. Skip all the wannabe italian pasta joints along Columbus and come hither to Trattoria Contadina! This is one of my favorite places in the city. It's a quaint restaurant perched on a hill full of life and pasta.")
Review.create(business_id: business7.id, user_id: user9.id, rating: 5, body: "This is a great, intimate old school restaurant that great for a romantic date or catching up with friends! the service here is attentive and warm, Nancy was our server and there was a slight hiccup with our order but we didn't mind since she was so kind to us that we understood that mistakes happen! I wish i got the name of the man who constantly brought us bread and made sure our table was clean!")
Review.create(business_id: business7.id, user_id: user10.id, rating: 3, body: "I had a great time dining here but I just wish the entrees were better. The salad was okay. The dessert mediocre. I really really wanted to like this place, since it is so close to my house but atlas it was only okay.")
Review.create(business_id: business7.id, user_id: user11.id, rating: 5, body: "If you want authentic Italian food, head over to this wonderful restaurant where you are treated like family. We had a wonderful meal and evening.  If you want to get in and out, this is not the place to go.  If you want to experience a true Italian meal and spend a few relaxing hours, walk over to Trattoria Contadina.")
Review.create(business_id: business7.id, user_id: user12.id, rating: 3, body: "Don't get me wrong, I like the resturant and food. But there are a few easy things they can do better. Why would you take the plates away while one person is still eating?  It embarrasses the person still eating.  The pasta is kinda soft. Don't boil it for so long. The little things would make this place so much better.")
Review.create(business_id: business7.id, user_id: user13.id, rating: 5, body: "Went to this restaurant recently for the first time with 2 friends. The appetizers, entrees and wine were perfection. Highly recommend the gnocchi in tomato cream sauce. Service is warm and personable.")
Review.create(business_id: business7.id, user_id: user14.id, rating: 2, body: "This is the quintessential neighborhood trattoria, looks-wise. Cute as a bug. Excellent service. And the spaghetti with meatballs looked great. Unfortunately their signature pasta (which had prosciutto, sun dried tomatoes, peas, garlic, tasteless tomato cream sauce and some tubular pasta) was just awful. The special risotto was also devoid of flavor.")

Review.create(business_id: business8.id, user_id: user15.id, rating: 4, body: "Nick's is a taco stand (kinda) in a dive bar named Rouge.  This is a tough one to explain, guess you have to come here to experience it.  Regardless I'm glad we came here as lunch was wonderful.")
Review.create(business_id: business8.id, user_id: user16.id, rating: 3, body: "I came to the attached bar to watch football on Sunday... and I've been super excited to come here. But honestly, like... I just wasn't impressed. I ordered 3 tacos: fish, shrimp, and the fried chicken. So the fish was honestly delicious. The fried chicken and shrimp were both EXTREMELY dry.")
Review.create(business_id: business8.id, user_id: user17.id, rating: 4, body: "This place is a block away from my clay studio and I have become addicted to their Fish tacos. Not the grilled but the fried version, done Nick's way, is what I think about when hunger strikes. They fry one of the tortillas so it has a cup shape and the second tortilla they leave soft wrapped over the fried one and I just looooove that crunch!")
Review.create(business_id: business8.id, user_id: user18.id, rating: 2, body: "I'm husband and I can here on taco Tuesday and with as much hype as I read in these reviews, I was thoroughly disappointed for a couple of reasons. The service was horrible, and it's SO damn loud in this place on Tuesday. Probably won't be back.")
Review.create(business_id: business8.id, user_id: user19.id, rating: 5, body: "Best taco tuesdays in the city!! :) I love Nick's and the tacos are just GIGANTIC, seriously.. two is more than enough! They add a looot of meat and beans, and guac and salsa, its the perfect taco to be honest.")
Review.create(business_id: business8.id, user_id: user20.id, rating: 4, body: "Very solid for Taco Tuesday. They stuff their tacos and honestly 2 is enough for $7. The meat is a bit dry but with the sauce it balances out. the red sauce is horrid but the green one is quite delicious. We also got the chips and that was a decent deal with all the guac and accompanying veggies.")
Review.create(business_id: business8.id, user_id: user21.id, rating: 5, body: "Had an amazing time. Had a whole pitcher of margaritas at happy hour for $20! It was awesome. The street tacos were dry, but the chips were great!")

Review.create(business_id: business9.id, user_id: user1.id, rating: 4, body: "We had such a lovely evening here with out of town relatives. I thought it was a bit dressier than what others thought. I considered it to be a 'nice' restaurant not casual for those prices. Lobster thermador was amazing! So rich.")
Review.create(business_id: business9.id, user_id: user2.id, rating: 4, body: "This is one of those spots that I've heard about and was told to try, but there are so many great places to eat in SF, that I had not yet tried it...until this trip. Boy was I glad that we did. I had the Crab Thermador which was very delicious.")
Review.create(business_id: business9.id, user_id: user22.id, rating: 5, body: "Iconic SF Resturant. We enjoying coming here, staff is always friendly and knowledgeable. Food never disappoints. Not a bad seat in the house! The ambiance is part of the charm of Scoma's, it's tucked away and a little hidden but well worth going! ")
Review.create(business_id: business9.id, user_id: user23.id, rating: 5, body: "This is absolutely positively the best seafood place to eat in the wharf when you're up in San Francisco. I order the fried seafood combo scallops shrimp and fish not one bit of grease soggy seafood. They make there own house pickles. Try the poor mans. Cioppino is loaded with fresh fish clams muscles shrimping a tomato broth. The lobster bisque is the bomb. Can't wait for our next trip to Scoma's.")
Review.create(business_id: business9.id, user_id: user24.id, rating: 5, body: "This is officially my favorite restaurant in San Francisco. For years my dad raves about how good it was but I never went. And boy do I wish I had tried it earlier.")
Review.create(business_id: business9.id, user_id: user25.id, rating: 4, body: "Be sure to make reservations! I came around 5pm and was surprised how packed it was. I recommend the Dungeness crab Thermidor. It was amazing! Filled with lots of fresh crab. So hearty and very comforting. It was a little pricier than other restaurants but what do you expect since this restaurant is right on the pier.")
Review.create(business_id: business9.id, user_id: user14.id, rating: 4, body: "Came back 3rd time for lunch along with my wife. Always fantastic food ang great service. We were greeted with a smile of their staff, accommodating as always, and the food was prepared very well. The salmon and clam chowder was really delicious.")

Review.create(business_id: business10.id, user_id: user2.id, rating: 4, body: "The Boardroom was the perfect place to post up and enjoy a few hours of Football Sunday. Came to San Francisco for the first time and as much as I wanted to sight see and walk around and do this and that, Football Sunday is Football Sunday, we needed to be somewhere with a big television and crazed fans regardless of what city we were in.")
Review.create(business_id: business10.id, user_id: user7.id, rating: 5, body: "Came in on a whim from the east bay, which we rarely do. Since we were early we decided to catch the Mexico Korea World Cup soccer game. Great small neighborhood crowd. Inexpensive drinks. Pretentiousness left at the door.")
Review.create(business_id: business10.id, user_id: user5.id, rating: 5, body: "This is definitely one of my favorite sports bars in SF. The service is fantastic looking at you Justin and JP. Love y'all. But they have very good nibbles for a sports bar. I've had the tots, poutine, wings, hummus, chicken tenders, and quesadillas; all have been really tasty. Def go with the wings, I love them, Louisiana or buffalo, I like spicy. They have of course ranch or Bleu cheese as dipping sauces for the wings and bring you crema and salsa with the quesadillas.")
Review.create(business_id: business10.id, user_id: user13.id, rating: 2, body: "Not a great bar for a night cap. Bartender was rude to my friend and I. She didn't have her ID but he's never ID her then he does. But more it was his attitude. It was my birthday and he wouldn't even let her buy me a shot. She proved she was of age to.")
Review.create(business_id: business10.id, user_id: user19.id, rating: 3, body: "I was honestly going to give this place four stars--A litte far for me to come regularly, but it's a small cozy bar that is great for locals. This joint has good bar food, drinks, and snacks. However, it was brought to my attention from one of my friends that I came with that he was rudely called out by the bartender for not tipping before he even had a chance to do so. While I didn't directly experience this, I'm disappointed this happened as a first impression here.")
Review.create(business_id: business10.id, user_id: user16.id, rating: 3, body: "Came out here to watch the Warriors game last night and it was a pretty chill spot. Nothing fancy, definitely divey and small, but the crowd was chill and the staff was friendly. One big projection screen and several flat screens through out. Great selection of spirits.")
Review.create(business_id: business10.id, user_id: user17.id, rating: 5, body: "Wow. This spot came out of nowhere and really surprised me. It doesn't look like much. Looks just like another random sports bar. But when I got my bill for drinks, they were charging $2 pints and shots during happy hour. I was like this can't be right but it was.")


# Review.create(business_id: business4.id, user_id: user3.id, rating: 5, body: "Easily one of the best pizza spots in SF. The pizza crust is chewy, slightly sourdoughy, soft, and the perfect amount of bubble and char. We always get the Bianca which is a white pie with kale, garlic, and mozzarella and we do an add-on for sausage.")
# Review.create(business_id: business4.id, user_id: user4.id, rating: 5, body: "My favorite pizza! I'm not actually a lover of pizza because I don't like bread. I enjoy pizza once in a while or when I drink, but I love other foods more. But wow, the pizza here is amazing where I'd crave it sober. The dough is so soft but in the best way... most crusts I've had on pizzas are usually dry or hard or empty/airy inside but the crust on these is soft and yummy.")
# Review.create(business_id: business4.id, user_id: user5.id, rating: 4, body: "I adored the pizza. A nice thin bubbly crust. And just the right amount of toppings. My favorite pizza is a pepperoni and mushroom, so this hit the spot. Sitting at the counter was a bit uncomfortable, so I recommend trying to get a table if possible. The heat from the pizza oven made it a little too toasty.")
# Review.create(business_id: business4.id, user_id: user6.id, rating: 5, body: "This has to be the best pizza in SF. The dough is light , springy and just the right texture for thin crust pizza. The toppings are sophisticated and special. It's not just a marinara pizza: it's toasted garlic and fresh oregano. I had the squash pizza with smoked cheese chili's honey and thyme. Great combination of heat and hearty and herb.")
# Review.create(business_id: business4.id, user_id: user8.id, rating: 5, body: "Had dinner and a private event here (covered garden patio in the back) and I was blown away both times. The staff for our private event went above and beyond, catered to different dietary needs seamlessly, were kind, thoughtful and incredibly attentive. We had a wonderful time and the food was just as amazing as the service. Delicious pizzas and small plates. Felt so lucky to find this gem. Thank you!!!")
# Review.create(business_id: business4.id, user_id: user9.id, rating: 3, body: "Very casual ambiance, good service, a bit too expensive. The seating arrangement was uncomfortable. I enjoyed my pizza but it was not one of the best of SF. Burrata appetizer was good but nothing to rave about. Desserts variety is limited.")
# Review.create(business_id: business4.id, user_id: user10.id, rating: 5, body: "The pizza is Neapolitan style, cooked perfectly (with deliciously chewy crust), and high-quality ingredients. The pizza is also prepared/cooked quickly (less than 5-10 min). You can make your pizza vegan by omitting cheese...the pizza is so good that won't miss it.")
  