# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#  movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#  Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
Business.destroy_all
Review.destroy_all
Category.destroy_all
BusinessCategory.destroy_all


demo = User.create(first_name: 'Demo', last_name: 'User', email: 'noemail@email.com', password: 'password', zip_code: '94018')
user1 = User.create(first_name: 'Mary', last_name: 'Poppins', email: 'mary123@mail.com', password: 'password', zip_code: '94012')
user2 = User.create(first_name: 'Mike', last_name: 'Smith', email: 'mikesmith@mail.com', password: 'password', zip_code: '94016')
user3 = User.create(first_name: 'Jessica', last_name: 'Jones', email: 'jessicaaaaaa@mail.com', password: 'password', zip_code: '94013')
user4 = User.create(first_name: 'Serena', last_name: 'Williams', email: 'ilovetennis@mail.com', password: 'password', zip_code: '94014')
user5 = User.create(first_name: 'Joe', last_name: 'Bruin', email: 'bearbearbear@mail.com', password: 'password', zip_code: '90024')
user6 = User.create(first_name: 'Matt', last_name: 'Miller', email: 'mercerindisguise@mail.com', password: 'password', zip_code: '90210')
user7 = User.create(first_name: 'Finn', last_name: 'Human', email: 'jakethedog@mail.com', password: 'password', zip_code: '94015')
user8 = User.create(first_name: 'Wilson', last_name: 'Coconut', email: 'imlost@mail.com', password: 'password', zip_code: '94019')
user9 = User.create(first_name: 'Sandy', last_name: 'Star', email: 'bobthesponge@mail.com', password: 'password', zip_code: '94017')
user10 = User.create(first_name: 'Elaine', last_name: 'Wong', email: 'tofurkey@mail.com', password: 'password', zip_code: '91001')
user11 = User.create(first_name: 'Albert', last_name: 'Coulson', email: 'pianoman@mail.com', password: 'password', zip_code: '94133')
user12 = User.create(first_name: 'Lily', last_name: 'Janeway', email: 'flowersaregreat@mail.com', password: 'password', zip_code: '94105')
user13 = User.create(first_name: 'Jackie', last_name: 'Jung', email: 'idokungfu@mail.com', password: 'password', zip_code: '94019')
user14 = User.create(first_name: 'Ryan', last_name: 'Chan', email: 'eateateatme@mail.com', password: 'password', zip_code: '94012')
user15 = User.create(first_name: 'Elizabeth', last_name: 'Bennett', email: 'bookgal13@mail.com', password: 'password', zip_code: '94011')
user16 = User.create(first_name: 'Ben', last_name: 'Stiller', email: 'moviesallday@mail.com', password: 'password', zip_code: '90024')
user17 = User.create(first_name: 'Logan', last_name: 'Clarke', email: 'supesnotsuits@mail.com', password: 'password', zip_code: '90025')
user18 = User.create(first_name: 'Adam', last_name: 'Anderson', email: 'mranderson@mail.com', password: 'password', zip_code: '91733')
user19 = User.create(first_name: 'Michelle', last_name: 'Warren', email: 'bestseatsinthehouse@mail.com', password: 'password', zip_code: '91732')
user20 = User.create(first_name: 'Jake', last_name: 'Carter', email: 'someguy11@mail.com', password: 'password', zip_code: '91731')
user21 = User.create(first_name: 'Thomas', last_name: 'Ward', email: 'yoursmileiscute@mail.com', password: 'password', zip_code: '94012')
user22 = User.create(first_name: 'Catherine', last_name: 'Simmons', email: 'persimmon@mail.com', password: 'password', zip_code: '90211')
user23 = User.create(first_name: 'Hannah', last_name: 'Foster', email: 'fosterlove@mail.com', password: 'password', zip_code: '90024')
user24 = User.create(first_name: 'Sofia', last_name: 'Perez', email: 'sofiathegreat@mail.com', password: 'password', zip_code: '94133')
user25 = User.create(first_name: 'Quyen', last_name: 'Tran', email: 'qtpie@mail.com', password: 'password', zip_code: '94132')

demo.photo.attach(io: File.open('./app/assets/images/user/demo.png'), filename: 'demo.png')
user1.photo.attach(io: File.open('./app/assets/images/user/user1.jpg'), filename: 'user1.jpg')
user2.photo.attach(io: File.open('./app/assets/images/user/user2.jpg'), filename: 'user2.jpg')
user3.photo.attach(io: File.open('./app/assets/images/user/user3.jpg'), filename: 'user3.jpg')
user4.photo.attach(io: File.open('./app/assets/images/user/user4.jpg'), filename: 'user4.jpg')
user5.photo.attach(io: File.open('./app/assets/images/user/user5.jpg'), filename: 'user5.jpg')
user6.photo.attach(io: File.open('./app/assets/images/user/user6.jpg'), filename: 'user6.jpg')
user7.photo.attach(io: File.open('./app/assets/images/user/user7.jpg'), filename: 'user7.jpg')
user8.photo.attach(io: File.open('./app/assets/images/user/user8.jpg'), filename: 'user8.jpg')
user9.photo.attach(io: File.open('./app/assets/images/user/user9.jpg'), filename: 'user9.jpg')
user10.photo.attach(io: File.open('./app/assets/images/user/user10.jpeg'), filename: 'user10.jpeg')
user11.photo.attach(io: File.open('./app/assets/images/user/user11.jpg'), filename: 'user11.jpg')
user12.photo.attach(io: File.open('./app/assets/images/user/user12.jpg'), filename: 'user12.jpg')
user13.photo.attach(io: File.open('./app/assets/images/user/user13.jpg'), filename: 'user13.jpg')
user14.photo.attach(io: File.open('./app/assets/images/user/user14.jpg'), filename: 'user14.jpg')
user15.photo.attach(io: File.open('./app/assets/images/user/user15.jpg'), filename: 'user15.jpg')
user16.photo.attach(io: File.open('./app/assets/images/user/user16.jpg'), filename: 'user16.jpg')
user17.photo.attach(io: File.open('./app/assets/images/user/user17.jpg'), filename: 'user17.jpg')
user18.photo.attach(io: File.open('./app/assets/images/user/user18.jpg'), filename: 'user18.jpg')
user19.photo.attach(io: File.open('./app/assets/images/user/user19.jpg'), filename: 'user19.jpg')
user20.photo.attach(io: File.open('./app/assets/images/user/user20.png'), filename: 'user20.png')
user21.photo.attach(io: File.open('./app/assets/images/user/user21.jpg'), filename: 'user21.jpg')
user22.photo.attach(io: File.open('./app/assets/images/user/user22.jpg'), filename: 'user22.jpg')
user23.photo.attach(io: File.open('./app/assets/images/user/user23.jpg'), filename: 'user23.jpg')
user24.photo.attach(io: File.open('./app/assets/images/user/user24.jpg'), filename: 'user24.jpg')
user25.photo.attach(io: File.open('./app/assets/images/user/user25.jpg'), filename: 'user25.jpg')

business1 = Business.create(business_name: "Fog Harbor Fish House", address: "Pier 39 Ste A-202", city: "San Francisco", state: "CA", zip_code: "94133", latitude: 37.80964, longitude: -122.41025, phone: "(415) 421-2442", website: "fogharbor.com", price: '$$')
business2 = Business.create(business_name: "Marufuku Ramen", address: "1581 Webster St", city: "San Francisco", state: "CA", zip_code: "94115", latitude: 37.78537, longitude: -122.43146, phone: "(415) 872-9786", website: "marufukuramen.com", price: '$$')
business3 = Business.create(business_name: "The House", address: "1230 Grant Ave", city: "San Francisco", state: "CA", zip_code: "94133", latitude: 37.797952, longitude: -122.407148, phone: "(415) 986-8612", website: "thehse.com", price: '$$$')
business4 = Business.create(business_name: "Sotto Mare Oysteria and Seafood", address: "552 Green St", city: "San Francisco", state: "CA", zip_code: "94133", latitude: 37.799670, longitude: -122.408290, phone: "(415) 398-3181", website: "sottomaresf.com", price: '$$')
business5 = Business.create(business_name: "Liholiho Yacht Club", address: "871 Sutter St", city: "San Francisco", state: "CA", zip_code: "94109", latitude: 37.788180, longitude: -122.414580, phone: "(415) 440-5446", website: "lycsf.com", price: '$$$')
business6 = Business.create(business_name: "Tacorea", address: "809 Bush St", city: "San Francisco", state: "CA", zip_code: "94108", latitude: 37.789725, longitude: -122.410900, phone: "(415) 885-1325", website: "tacorea.com", price: '$')
business7 = Business.create(business_name: "Trattoria Contadina", address: "1800 Mason St", city: "San Francisco", state: "CA", zip_code: "94133", latitude: 37.800180, longitude: -122.412280, phone: "(415) 982-5728", website: "trattoriacontadina.com", price: '$$')
business8 = Business.create(business_name: "Nick's Crispy Tacos", address: "1500 Broadway", city: "San Francisco", state: "CA", zip_code: "94109", latitude: 37.796050, longitude: -122.422110, phone: "(415) 409-8226", website: "nickscrispytacos.com", price: '$')
business9 = Business.create(business_name: "Scoma Restaurant", address: "1965 Al Scoma Way", city: "San Francisco", state: "CA", zip_code: "94133", latitude: 37.809030, longitude: -122.418020, phone: "(415) 771-4383", website: "scomas.com", price: '$$$')
business10 = Business.create(business_name: "The Boardroom", address: "1600 Powell St", city: "San Francisco", state: "CA", zip_code: "94133", latitude: 37.799470, longitude: -122.410430, phone: "(415) 982-8898", website: "boardroomsf.com", price: '$')
business11 = Business.create(business_name: "Mama's On Washington Square", address: "1701 Stockton St", city: "San Francisco", state: "CA", zip_code: "94133", latitude: 37.801486, longitude: -122.409553, phone: "(415) 362-6421", website: "mamas-sf.com", price: '$$')
business12 = Business.create(business_name: "Noah's Bagels", address: "100 Bush St", city: "San Francisco", state: "CA", zip_code: "94104", latitude: 37.791510, longitude: -122.399906, phone: "(415) 433-9682", website: "noahs.com", price: '$')
business13 = Business.create(business_name: "Samovar Tea", address: "730 Howard St", city: "San Francisco", state: "CA", zip_code: "94103", latitude: 37.784650, longitude: -122.402345, phone: "(415) 227-9400", website: "samovartea.com", price: '$$')
business14 = Business.create(business_name: "Ace Wasabi Sushi", address: "3339 Steiner St", city: "San Francisco", state: "CA", zip_code: "94123", latitude: 37.800212, longitude: -122.437972, phone: "(415) 567-4903", website: "acewasabisf.com", price: '$$')
business15 = Business.create(business_name: "Kuma Sushi + Sake", address: "1040 Polk St", city: "San Francisco", state: "CA", zip_code: "94109", latitude: 37.786601, longitude: -122.419777, phone: "(415) 962-7400", website: "kumasf.com", price: '$$')
business16 = Business.create(business_name: "Good Mong Kok Bakery", address: "1039 Stockton St", city: "San Francisco", state: "CA", zip_code: "94108", latitude: 37.790276, longitude: -122.407147, phone: "(415) 397-2688", website: "goodmongkok.com", price: '$')

business1.photo.attach(io: File.open('./app/assets/images/business/1-fog/fog1.jpg'), filename: 'fog1-1.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog1.jpg'), filename: 'fog1.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog2.jpg'), filename: 'fog2.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog3.jpg'), filename: 'fog3.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog4.jpg'), filename: 'fog4.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog5.jpg'), filename: 'fog5.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog6.jpg'), filename: 'fog6.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog7.jpg'), filename: 'fog7.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog8.jpg'), filename: 'fog8.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog9.jpg'), filename: 'fog9.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog10.jpg'), filename: 'fog10.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog11.jpg'), filename: 'fog11.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog12.jpg'), filename: 'fog12.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog13.jpg'), filename: 'fog13.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog14.jpg'), filename: 'fog14.jpg')
business1.pics.attach(io: File.open('./app/assets/images/business/1-fog/fog15.jpg'), filename: 'fog15.jpg')

business2.photo.attach(io: File.open('./app/assets/images/business/2-maru/maru1.jpg'), filename: 'maru1-1.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru1.jpg'), filename: 'maru1.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru2.jpg'), filename: 'maru2.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru3.jpg'), filename: 'maru3.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru4.jpg'), filename: 'maru4.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru5.jpg'), filename: 'maru5.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru6.jpg'), filename: 'maru6.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru7.jpg'), filename: 'maru7.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru8.jpg'), filename: 'maru8.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru9.jpg'), filename: 'maru9.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru10.jpg'), filename: 'maru10.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru11.jpg'), filename: 'maru11.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru12.jpg'), filename: 'maru12.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru13.jpg'), filename: 'maru13.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru14.jpg'), filename: 'maru14.jpg')
business2.pics.attach(io: File.open('./app/assets/images/business/2-maru/maru15.jpg'), filename: 'maru15.jpg')

business3.photo.attach(io: File.open('./app/assets/images/business/3-house/house1.jpg'), filename: 'house1-1.jpg')
business3.pics.attach(io: File.open('./app/assets/images/business/3-house/house1.jpg'), filename: 'house1.jpg')
business3.pics.attach(io: File.open('./app/assets/images/business/3-house/house2.jpg'), filename: 'house2.jpg')
business3.pics.attach(io: File.open('./app/assets/images/business/3-house/house3.jpg'), filename: 'house3.jpg')
business3.pics.attach(io: File.open('./app/assets/images/business/3-house/house4.jpg'), filename: 'house4.jpg')
business3.pics.attach(io: File.open('./app/assets/images/business/3-house/house5.jpg'), filename: 'house5.jpg')
business3.pics.attach(io: File.open('./app/assets/images/business/3-house/house6.jpg'), filename: 'house6.jpg')
business3.pics.attach(io: File.open('./app/assets/images/business/3-house/house7.jpg'), filename: 'house7.jpg')
business3.pics.attach(io: File.open('./app/assets/images/business/3-house/house8.jpg'), filename: 'house8.jpg')
business3.pics.attach(io: File.open('./app/assets/images/business/3-house/house9.jpg'), filename: 'house9.jpg')
business3.pics.attach(io: File.open('./app/assets/images/business/3-house/house10.jpg'), filename: 'house10.jpg')
business3.pics.attach(io: File.open('./app/assets/images/business/3-house/house11.jpg'), filename: 'house11.jpg')
business3.pics.attach(io: File.open('./app/assets/images/business/3-house/house12.jpg'), filename: 'house12.jpg')
business3.pics.attach(io: File.open('./app/assets/images/business/3-house/house13.jpg'), filename: 'house13.jpg')

business4.photo.attach(io: File.open('./app/assets/images/business/4-sotto/sotto1.jpg'), filename: 'sotto1-1.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto1.jpg'), filename: 'sotto1.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto2.jpg'), filename: 'sotto2.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto3.jpg'), filename: 'sotto3.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto4.jpg'), filename: 'sotto4.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto5.jpg'), filename: 'sotto5.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto6.jpg'), filename: 'sotto6.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto7.jpg'), filename: 'sotto7.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto8.jpg'), filename: 'sotto8.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto9.jpg'), filename: 'sotto9.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto10.jpg'), filename: 'sotto10.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto11.jpg'), filename: 'sotto11.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto12.jpg'), filename: 'sotto12.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto13.jpg'), filename: 'sotto13.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto14.jpg'), filename: 'sotto14.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto15.jpg'), filename: 'sotto15.jpg')
business4.pics.attach(io: File.open('./app/assets/images/business/4-sotto/sotto16.jpg'), filename: 'sotto16.jpg')

business5.photo.attach(io: File.open('./app/assets/images/business/5-liho/liho1.jpg'), filename: 'liho1-1.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho1.jpg'), filename: 'liho1.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho2.jpg'), filename: 'liho2.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho3.jpg'), filename: 'liho3.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho4.jpg'), filename: 'liho4.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho5.jpg'), filename: 'liho5.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho6.jpg'), filename: 'liho6.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho7.jpg'), filename: 'liho7.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho8.jpg'), filename: 'liho8.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho9.jpg'), filename: 'liho9.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho10.jpg'), filename: 'liho10.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho11.jpg'), filename: 'liho11.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho12.jpg'), filename: 'liho12.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho13.jpg'), filename: 'liho13.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho14.jpg'), filename: 'liho14.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho15.jpg'), filename: 'liho15.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho16.jpg'), filename: 'liho16.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho17.jpg'), filename: 'liho17.jpg')
business5.pics.attach(io: File.open('./app/assets/images/business/5-liho/liho18.jpg'), filename: 'liho18.jpg')

business6.photo.attach(io: File.open('./app/assets/images/business/6-taco/taco1.jpg'), filename: 'taco1-1.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco1.jpg'), filename: 'taco1.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco2.jpg'), filename: 'taco2.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco3.jpg'), filename: 'taco3.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco4.jpg'), filename: 'taco4.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco5.jpg'), filename: 'taco5.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco6.jpg'), filename: 'taco6.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco7.jpg'), filename: 'taco7.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco8.jpg'), filename: 'taco8.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco9.jpg'), filename: 'taco9.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco10.jpg'), filename: 'taco10.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco11.jpg'), filename: 'taco11.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco12.jpg'), filename: 'taco12.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco13.jpg'), filename: 'taco13.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco14.jpg'), filename: 'taco14.jpg')
business6.pics.attach(io: File.open('./app/assets/images/business/6-taco/taco15.jpg'), filename: 'taco15.jpg')

business7.photo.attach(io: File.open('./app/assets/images/business/7-tratt/tratt1.jpg'), filename: 'tratt1-1.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt1.jpg'), filename: 'tratt1.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt2.jpg'), filename: 'tratt2.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt3.jpg'), filename: 'tratt3.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt4.jpg'), filename: 'tratt4.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt5.jpg'), filename: 'tratt5.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt6.jpg'), filename: 'tratt6.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt7.jpg'), filename: 'tratt7.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt8.jpg'), filename: 'tratt8.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt9.jpg'), filename: 'tratt9.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt10.jpg'), filename: 'tratt10.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt11.jpg'), filename: 'tratt11.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt12.jpg'), filename: 'tratt12.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt13.jpg'), filename: 'tratt13.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt14.jpg'), filename: 'tratt14.jpg')
business7.pics.attach(io: File.open('./app/assets/images/business/7-tratt/tratt15.jpg'), filename: 'tratt15.jpg')

business8.photo.attach(io: File.open('./app/assets/images/business/8-crisp/crisp1.jpg'), filename: 'crisp1-1.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp1.jpg'), filename: 'crisp1.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp2.jpg'), filename: 'crisp2.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp3.jpg'), filename: 'crisp3.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp4.jpg'), filename: 'crisp4.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp5.jpg'), filename: 'crisp5.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp6.jpg'), filename: 'crisp6.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp7.jpg'), filename: 'crisp7.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp8.jpg'), filename: 'crisp8.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp9.jpg'), filename: 'crisp9.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp10.jpg'), filename: 'crisp10.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp11.jpg'), filename: 'crisp11.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp12.jpg'), filename: 'crisp12.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp13.jpg'), filename: 'crisp13.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp14.jpg'), filename: 'crisp14.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp15.jpg'), filename: 'crisp15.jpg')
business8.pics.attach(io: File.open('./app/assets/images/business/8-crisp/crisp16.jpg'), filename: 'crisp16.jpg')

business9.photo.attach(io: File.open('./app/assets/images/business/9-scoma/scoma1.jpg'), filename: 'scoma1-1.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma1.jpg'), filename: 'scoma1.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma2.jpg'), filename: 'scoma2.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma3.jpg'), filename: 'scoma3.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma4.jpg'), filename: 'scoma4.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma5.jpg'), filename: 'scoma5.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma6.jpg'), filename: 'scoma6.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma7.jpg'), filename: 'scoma7.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma8.jpg'), filename: 'scoma8.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma9.jpg'), filename: 'scoma9.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma10.jpg'), filename: 'scoma10.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma11.jpg'), filename: 'scoma11.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma12.jpg'), filename: 'scoma12.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma13.jpg'), filename: 'scoma13.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma14.jpg'), filename: 'scoma14.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma15.jpg'), filename: 'scoma15.jpg')
business9.pics.attach(io: File.open('./app/assets/images/business/9-scoma/scoma16.jpg'), filename: 'scoma16.jpg')

business10.photo.attach(io: File.open('./app/assets/images/business/10-board/board1.jpg'), filename: 'board1-1.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board1.jpg'), filename: 'board1.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board2.jpg'), filename: 'board2.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board3.jpg'), filename: 'board3.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board4.jpg'), filename: 'board4.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board5.jpg'), filename: 'board5.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board6.jpg'), filename: 'board6.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board7.jpg'), filename: 'board7.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board8.jpg'), filename: 'board8.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board9.jpg'), filename: 'board9.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board10.jpg'), filename: 'board10.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board11.jpg'), filename: 'board11.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board12.jpg'), filename: 'board12.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board13.jpg'), filename: 'board13.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board14.jpg'), filename: 'board14.jpg')
business10.pics.attach(io: File.open('./app/assets/images/business/10-board/board15.jpg'), filename: 'board15.jpg')

business11.photo.attach(io: File.open('./app/assets/images/business/11-mamas/mamas0.jpg'), filename: 'mamas0-1.jpg')
business11.pics.attach(io: File.open('./app/assets/images/business/11-mamas/mamas0.jpg'), filename: 'mamas0.jpg')
business11.pics.attach(io: File.open('./app/assets/images/business/11-mamas/mamas1.jpg'), filename: 'mamas1.jpg')
business11.pics.attach(io: File.open('./app/assets/images/business/11-mamas/mamas2.jpg'), filename: 'mamas2.jpg')
business11.pics.attach(io: File.open('./app/assets/images/business/11-mamas/mamas3.jpg'), filename: 'mamas3.jpg')
business11.pics.attach(io: File.open('./app/assets/images/business/11-mamas/mamas4.jpg'), filename: 'mamas4.jpg')
business11.pics.attach(io: File.open('./app/assets/images/business/11-mamas/mamas5.jpg'), filename: 'mamas5.jpg')
business11.pics.attach(io: File.open('./app/assets/images/business/11-mamas/mamas6.jpg'), filename: 'mamas6.jpg')
business11.pics.attach(io: File.open('./app/assets/images/business/11-mamas/mamas7.jpg'), filename: 'mamas7.jpg')
business11.pics.attach(io: File.open('./app/assets/images/business/11-mamas/mamas8.jpg'), filename: 'mamas8.jpg')
business11.pics.attach(io: File.open('./app/assets/images/business/11-mamas/mamas9.jpg'), filename: 'mamas9.jpg')
business11.pics.attach(io: File.open('./app/assets/images/business/11-mamas/mamas10.jpg'), filename: 'mamas10.jpg')

business12.photo.attach(io: File.open('./app/assets/images/business/12-noahs/noahs0.jpg'), filename: 'noahs0-1.jpg')
business12.pics.attach(io: File.open('./app/assets/images/business/12-noahs/noahs0.jpg'), filename: 'noahs0.jpg')
business12.pics.attach(io: File.open('./app/assets/images/business/12-noahs/noahs1.jpg'), filename: 'noahs1.jpg')
business12.pics.attach(io: File.open('./app/assets/images/business/12-noahs/noahs2.jpg'), filename: 'noahs2.jpg')
business12.pics.attach(io: File.open('./app/assets/images/business/12-noahs/noahs3.jpg'), filename: 'noahs3.jpg')
business12.pics.attach(io: File.open('./app/assets/images/business/12-noahs/noahs4.jpg'), filename: 'noahs4.jpg')
business12.pics.attach(io: File.open('./app/assets/images/business/12-noahs/noahs5.jpg'), filename: 'noahs5.jpg')

business13.photo.attach(io: File.open('./app/assets/images/business/13-samovar/samovar0.jpg'), filename: 'samovar0-1.jpg')
business13.photo.attach(io: File.open('./app/assets/images/business/13-samovar/samovar0.jpg'), filename: 'samovar0.jpg')
business13.pics.attach(io: File.open('./app/assets/images/business/13-samovar/samovar1.jpg'), filename: 'samovar1.jpg')
business13.pics.attach(io: File.open('./app/assets/images/business/13-samovar/samovar2.jpg'), filename: 'samovar2.jpg')
business13.pics.attach(io: File.open('./app/assets/images/business/13-samovar/samovar3.jpg'), filename: 'samovar3.jpg')
business13.pics.attach(io: File.open('./app/assets/images/business/13-samovar/samovar4.jpg'), filename: 'samovar4.jpg')
business13.pics.attach(io: File.open('./app/assets/images/business/13-samovar/samovar5.jpg'), filename: 'samovar5.jpg')
business13.pics.attach(io: File.open('./app/assets/images/business/13-samovar/samovar6.jpg'), filename: 'samovar6.jpg')
business13.pics.attach(io: File.open('./app/assets/images/business/13-samovar/samovar7.jpg'), filename: 'samovar7.jpg')
business13.pics.attach(io: File.open('./app/assets/images/business/13-samovar/samovar8.jpg'), filename: 'samovar8.jpg')
business13.pics.attach(io: File.open('./app/assets/images/business/13-samovar/samovar9.jpg'), filename: 'samovar9.jpg')
business13.pics.attach(io: File.open('./app/assets/images/business/13-samovar/samovar10.jpg'), filename: 'samovar10.jpg')

business14.photo.attach(io: File.open('./app/assets/images/business/14-ace/ace0.jpg'), filename: 'ace0-1.jpg')
business14.pics.attach(io: File.open('./app/assets/images/business/14-ace/ace0.jpg'), filename: 'ace0.jpg')
business14.pics.attach(io: File.open('./app/assets/images/business/14-ace/ace1.jpg'), filename: 'ace1.jpg')
business14.pics.attach(io: File.open('./app/assets/images/business/14-ace/ace2.jpg'), filename: 'ace2.jpg')
business14.pics.attach(io: File.open('./app/assets/images/business/14-ace/ace3.jpg'), filename: 'ace3.jpg')
business14.pics.attach(io: File.open('./app/assets/images/business/14-ace/ace4.jpg'), filename: 'ace4.jpg')
business14.pics.attach(io: File.open('./app/assets/images/business/14-ace/ace5.jpg'), filename: 'ace5.jpg')
business14.pics.attach(io: File.open('./app/assets/images/business/14-ace/ace6.jpg'), filename: 'ace6.jpg')

business15.photo.attach(io: File.open('./app/assets/images/business/15-kuma/kuma0.jpg'), filename: 'kuma0-1.jpg')
business15.pics.attach(io: File.open('./app/assets/images/business/15-kuma/kuma0.jpg'), filename: 'kuma0.jpg')
business15.pics.attach(io: File.open('./app/assets/images/business/15-kuma/kuma1.jpg'), filename: 'kuma1.jpg')
business15.pics.attach(io: File.open('./app/assets/images/business/15-kuma/kuma2.jpg'), filename: 'kuma2.jpg')
business15.pics.attach(io: File.open('./app/assets/images/business/15-kuma/kuma3.jpg'), filename: 'kuma3.jpg')
business15.pics.attach(io: File.open('./app/assets/images/business/15-kuma/kuma4.jpg'), filename: 'kuma4.jpg')
business15.pics.attach(io: File.open('./app/assets/images/business/15-kuma/kuma5.jpg'), filename: 'kuma5.jpg')
business15.pics.attach(io: File.open('./app/assets/images/business/15-kuma/kuma6.jpg'), filename: 'kuma6.jpg')
business15.pics.attach(io: File.open('./app/assets/images/business/15-kuma/kuma7.jpg'), filename: 'kuma7.jpg')
business15.pics.attach(io: File.open('./app/assets/images/business/15-kuma/kuma8.jpg'), filename: 'kuma8.jpg')
business15.pics.attach(io: File.open('./app/assets/images/business/15-kuma/kuma9.jpg'), filename: 'kuma9.jpg')
business15.pics.attach(io: File.open('./app/assets/images/business/15-kuma/kuma10.jpg'), filename: 'kuma10.jpg')

business16.photo.attach(io: File.open('./app/assets/images/business/16-good/good0.jpg'), filename: 'good0-1.jpg')
business16.pics.attach(io: File.open('./app/assets/images/business/16-good/good0.jpg'), filename: 'good0.jpg')
business16.pics.attach(io: File.open('./app/assets/images/business/16-good/good1.jpg'), filename: 'good1.jpg')
business16.pics.attach(io: File.open('./app/assets/images/business/16-good/good2.jpg'), filename: 'good2.jpg')
business16.pics.attach(io: File.open('./app/assets/images/business/16-good/good3.jpg'), filename: 'good3.jpg')
business16.pics.attach(io: File.open('./app/assets/images/business/16-good/good4.jpg'), filename: 'good4.jpg')
business16.pics.attach(io: File.open('./app/assets/images/business/16-good/good5.jpg'), filename: 'good5.jpg')
business16.pics.attach(io: File.open('./app/assets/images/business/16-good/good6.jpg'), filename: 'good6.jpg')
business16.pics.attach(io: File.open('./app/assets/images/business/16-good/good7.jpg'), filename: 'good7.jpg')

Review.create(business_id: business1.id, user_id: user1.id, rating: 5, body: "Had the best dinner here!! It is right off the pier with great views of the city, the bay, and most importantly, the Golden Gate Bridge! Make sure to get reservations and ask for a seat by the window to get a great sunset view at dinner.")
Review.create(business_id: business1.id, user_id: user2.id, rating: 5, body: "I ate here yesterday as my first meal ever in San Francisco and I was definitely not disappointed! I came at happy hour time (around 4pm) and so I got to take part of some happy hour specials while sitting at the bar. I came here for the sourdough bread bowl of clam chowder, and probably would've been fine with just that - but I couldn't pass up the fried lemon calamari on the happy hour menu for $7, and was very happy that I got that as well! (And some wine, of course).")
Review.create(business_id: business1.id, user_id: user6.id, rating: 3, body: "Came here for dinner last night. Its right on pier 39 overlooking the marina. Seevice was good. Our waitress was nice and attentive. Ambience was inviting. Food though was sub par, especially for the price.")
Review.create(business_id: business1.id, user_id: user9.id, rating: 4, body: "Seafood party! Love that you get on the wait list via Berp and avoid waiting around uncessarily. The clam chowder here was so amazing! It was creamy with pieces of clams and potato and I wanted to lick the bowl. Scallop, crab, and clam risotto was pretty tasty at first bite, but once I had a bite of the seafood penne pasta, it was like move over risotto. Red sauce is better than white sauce BTW.")
Review.create(business_id: business1.id, user_id: user12.id, rating: 4, body: "We made a reservation in advance, so we got the chance to sit by the window. The service was really attentive. We were taken good care of by the waiter all night. Recommended for dating and friends gathering. It is a touristy spot but it won't disappoint.")
Review.create(business_id: business1.id, user_id: user18.id, rating: 3, body: "Stopped in here for some chowder, and literally that was the only thing, although we ended up trying the oysters, too, which were small and not really that good (dry and sticky). Next time will have to ask to see what they have as the half dozen was not worth it. Front had plenty of seats though we still waited for a table.")
Review.create(business_id: business1.id, user_id: user19.id, rating: 5, body: "Outstanding service and great food... My wife and I came to SF for our anniversary and we wanted to try a good selection of the crab places. This restaurant was by far the best! We came back twice especially after our actual anniversary evening dinner was a complete bust at another restaurant.")

Review.create(business_id: business2.id, user_id: user4.id, rating: 5, body: "We went to the place because of the reviews on Berp. There was a big line and we had to wait for a while, but it was completely worth it! Ramen was so spicy and so so good.")
Review.create(business_id: business2.id, user_id: user5.id, rating: 4, body: "Best ramen in SF. The wait is long. We went for lunch and got on the waitlist, but still had to wait around 45 min. Broth was amazing and the egg was cooked perfectly. Definitely recommend this place.")
Review.create(business_id: business2.id, user_id: user6.id, rating: 2, body: "This is the saltiest Ramen we've ever had. My tongue still hurts. Got the special DX sizzling chicken. Chicken was hard and dry. Not sure if it was an off day, but none of the people in my group liked their food.")
Review.create(business_id: business2.id, user_id: user7.id, rating: 5, body: "Definitely the best ramen place I've been to in a long time i would have gotten the pork belly bun small bites (MarufukuBites) but was in a rush to go see a movie. It is located on the second floor of the far western building of Japantown near the theaters.")
Review.create(business_id: business2.id, user_id: user10.id, rating: 4, body: "Was the ramen really good? Yeah. Was it the best ramen I've had in SF? Probably. Was it the best in the Bay Area? Meh. I think there are definitely better ramen spots if you travel outside of SF. Marufuku just makes a solid bowl of ramen, which is pretty much standard fare for anywhere in Japan. There wasn't anything particularly special about it that makes me want to come back and battle the wait time again.")
Review.create(business_id: business2.id, user_id: user11.id, rating: 4, body: "Came here on a Sunday around opening time in hopes of not having to wait for very long, but still ended up having to put my name on a waitlist. Fortunately, we didn't have to wait too long and were seated within 30 mins. Overall, a good bowl of ramen! Would definitely be worth the wait (if the wait isn't too long).")

Review.create(business_id: business3.id, user_id: user1.id, rating: 5, body: "I love this place, and more than being happy, I have an inner sense of peace and joy as I imbibe the whole dining experience. No other restaurant makes me this happy. I hope The House stays this consistent and high quality for years to come.")
Review.create(business_id: business3.id, user_id: user11.id, rating: 5, body: "A perfect date spot for a potential significant other or someone that you've been with for a while, or just a friend. You won't be disappointed with the food that you order here!")
Review.create(business_id: business3.id, user_id: user21.id, rating: 5, body: "Make sure to make a reservation in advance. Place is small inside and gets super packed! Their food!!!! SOOOO GOOD!!! Ordered salmon fried rolls.")
Review.create(business_id: business3.id, user_id: user2.id, rating: 5, body: "We made a reservation (and I highly recommend you do the same, this place is super small and always packed). It was 6 of us at the table and we decided to order a bunch of different things off of their menu and just share it all. I am so glad we did that because everything was so delicious, flavorful and cooked to perfection. We were so excited about our meals, I totally forgot to take photos except for one! We loved our food and I know you will too! This place is a must try!")
Review.create(business_id: business3.id, user_id: user12.id, rating: 5, body: "The House is just exceptional! To be honest, I wasn't expecting much from this place because I assumed it would be a mish mash of glorified asian fusion but it blew me away! I'd definitely come back (either come really early or come with a reservation which can be hard to come by). This is a special occasion meal!")
Review.create(business_id: business3.id, user_id: user22.id, rating: 5, body: "Came by for dinner the other night and the experience was phenomenal as always! Reservations were available via Berp and we were seated upon arrival! The Black Cod was very fresh and perfectly cooked. The avocado roll complemented the dish perfectly!")
Review.create(business_id: business3.id, user_id: user24.id, rating: 5, body: "The House is damn good! With the reviews this restaurant has, I came in with high expectations and they were still exceeded. Definitely worthy of a visit. The restaurant is small, but the food is excellent. I have to say it was the best Asian fusion food I have had in SF. Dishes that stood out were the wasabi noodles with flatiron steak, a Korean short rib special, octopus, deep fried salman roll, and a scallop special. All were excellent!")
Review.create(business_id: business3.id, user_id: user25.id, rating: 5, body: "We were walking around North Beach and decided to check on Berp for a good place for lunch. The House popped up with 5 stars so we walked right over. It was past the usual lunch hour rush so we were seated within a minute of arriving.")

Review.create(business_id: business4.id, user_id: user3.id, rating: 5, body: "Great food great atmosphere! Went there on a week day night and it was packed. The restaurant is very small. But the food were so delicious! Absolutely loved it. One thing I did not like was their salad... it was disappointing. Looked like the stuff you put underneath tonkatsu lol But will definitely come back!")
Review.create(business_id: business4.id, user_id: user14.id, rating: 4, body: "Monday night at arrived at seven thirty waited about thirty minutes. The best cioppino? No. I think what makes it best is that they don't skimp out on the seafood and big portion. As for flavor? Nothing special. Me and my bf thought it was bland. As for the crab diavolo with linguine omggggg so freaking good. All the flavors were definitely there! Yummmmmy! I finished everything and I only got the half portion but it was good enough.")
Review.create(business_id: business4.id, user_id: user15.id, rating: 5, body: "This was our must-visit restaurant during our Cal trip. I was definitely looking forward to trying The Best Damn Cioppino since my friend kept raving about it! I must admit that it is probably the best cioppino I've ever had - and I'm from Seattle! We ordered some tasty oysters too! Sotto Mare is definitely an old-school San Francisco restaurant, which is awesome! Definitely stop in if you find yourself in North Beach!")
Review.create(business_id: business4.id, user_id: user16.id, rating: 5, body: "You really get that authentic Italian vibe once you step into the place. The smell of fresh seafood and freshly cooked pasta are just amazing. Definitely my favorite Italian restaurant in SF, so far. The restaurant is super crowded during the weekend and there is usually a long line so make sure to book beforehand. ")
Review.create(business_id: business4.id, user_id: user17.id, rating: 4, body: "Of course, we got the famous cioppino, which definitely lived up to the hype: tasty fresh seafood stewed in a nicely seasoned savory tomato broth with a sensibly portioned (read: they're not trying to rip you off by loading up on the cheap carbs) amount of al-dente pasta. Make sure to save some of the bread that they give you at the beginning of the meal in order to soak up that wonderful broth.")
Review.create(business_id: business4.id, user_id: user18.id, rating: 1, body: "I have absolutely NO idea what these 3300 reviewers see in this place. Coming from San Diego, I've had my share of seafood, and this place is comparable to Olive Garden at best. The bread was hard and cold. The oyster shooter, talk about an overstatement. Overall, as Ariana Grande would say: thank you, next.")
Review.create(business_id: business4.id, user_id: user19.id, rating: 5, body: "This is hands down one of the best restaurants I've ever eaten at. I was introduced to it a few years ago by one of my best friends and I've been coming back ever since. Have absolutely zero complaints about this place, come here immediately!")
Review.create(business_id: business4.id, user_id: user23.id, rating: 5, body: "BEST SEAFOOD IVE EVER HAD. The cioppino was INCREDIBLE and definitely big enough to share between 2-4 people. Would highly recommend. We were too late to get oysters but I plan on going back. The wait if you don't have a reservation can be long. We waited 2 hours, but it was WELL WORTH IT. incredible.")

Review.create(business_id: business5.id, user_id: user6.id, rating: 4, body: "Really enjoyed dinner at Liholiho. There were some dishes that weren't my favorite, but the others made up for it. We ordered way too much and had lots to take home, but was happy we got to try so many dishes. Highlights were the beef tongue buns and curry clams. The squid salad and fried oysters were also very delicious.")
Review.create(business_id: business5.id, user_id: user9.id, rating: 4, body: "Got to try the Housemade spam. It's less saltier than regular spam served on a bed of rice with pickles and furikake. I liked this dish a lot but I wish we had sheets of seaweed to wrap this with the rice. Musubi all day! Would they judge me if I bought in my own seaweed packets? Being that it's less salty I definitely didn't feel guilty for eating it and the pickles added some nice crunch to the dish.")
Review.create(business_id: business5.id, user_id: user12.id, rating: 5, body: "The restaurant scene is very casual and a touch loud! I loved how they brought the concept of an open kitchen to a whole new level with the opportunity to walk through the entire kitchen on the way back to the restaurant!")
Review.create(business_id: business5.id, user_id: user15.id, rating: 5, body: "Managed to walk in sans reservation the night before thanksgiving. The bar staff were incredibly knowledgeable, and the drinks were delicious. I enjoyed every dish we ate - the chicken liver mousse toast was my favourite. Almost gave only 4 stars as the boyfriend didn't enjoy the food, but he can write his own review. :)")
Review.create(business_id: business5.id, user_id: user18.id, rating: 4, body: "Finally get a chance to try this place out with a group of friend. Reservation is highly recommended for big party; It is always challenging to get so often you would have to make reservation 2 months in advance. The benefit of eating with a big group is you get to try many plates. Definitely recommend to others")
Review.create(business_id: business5.id, user_id: user21.id, rating: 3, body: "I've heard more than enough raves and reviews about this place that my expectations were HYPED. UP. But what they say is true - the higher expectations rise, they harder they fall (ish). Not to say that Liholiho was bad or a poor experience, but I found the food just...OK. Our meal turned out to be almost $200 after tax and tip. I'm not one to put a price tag on an experience and a good meal, but I honestly didn't see the worth in it.")
Review.create(business_id: business5.id, user_id: user24.id, rating: 4, body: "Overall, I really enjoyed the meal and the ambiance. The apps are the star here and if I got back, I'll order mainly apps and maybe share an entree. You try it out yourself and make a call but remember 1 month prior at midnight - Be online or you won't get a reasonable time for a dinner reso.")
Review.create(business_id: business5.id, user_id: user3.id, rating: 5, body: "Glad our lovely Elite friend Tracey A. booked the Ohana Table. Talk about a fabulous dining experience with the Yelp family from near & far. Hawaii peeps Terry and Peter were in the house. I've been wanting to try this place, but waited for the madness to die down. I can tell you it hasn't!")

Review.create(business_id: business6.id, user_id: user1.id, rating: 5, body: "A little taco parlor near Union Square and Masonic is our go to place when we are in the neighborhood. The seating is a little cozy and people watchers may enjoy sitting near the window.")
Review.create(business_id: business6.id, user_id: user2.id, rating: 4, body: "What a great place! Probably the best tacos I have had in San Francisco. Very convenient for a late night dinner. Price is very reasonable as well. Very nice overall.")
Review.create(business_id: business6.id, user_id: user3.id, rating: 5, body: "I've always enjoyed their California burrito, which is their version of a combination. It comes with onion, bell peppers, mushrooms and sausage. I like that they don't skimp on their portions their crust has a nice texture to it and they are very reasonably priced when you compare to other taco places in SOMA.")
Review.create(business_id: business6.id, user_id: user4.id, rating: 3, body: "Seeing all the reviews at this place made me want to come and check it out. And to be honest, to me, this place wasn't the most exciting taco place. I have started to become more inclined to eating Neapolitan style of tacos. I think though, this taco was just okay.")
Review.create(business_id: business6.id, user_id: user5.id, rating: 4, body: "Can't go wrong with a bulgogi taco. The California burrito was good, but a tad too much onion. They serve Drake's IPA which was good. Service was ok. The server checked on us a couple of times. Just not the friendliest.")
Review.create(business_id: business6.id, user_id: user6.id, rating: 5, body: "The food is good and the prices are very reasonable for the quality. They offer takeout and delivery too. Keep an eye out for the daily specials!")
Review.create(business_id: business6.id, user_id: user7.id, rating: 1, body: "I decided to get a taco from Tacorea while waiting for my laundry to complete across the road. At around 9:30 pm on Sunday it was slammed. The person taking orders was obviously having a bad day. He was out rightly rude to people who were simply placing orders.")

Review.create(business_id: business7.id, user_id: user8.id, rating: 5, body: "A cosy, Italian restaurant with some classically cooked food. Skip all the wannabe italian pasta joints along Columbus and come hither to Trattoria Contadina! This is one of my favorite places in the city. It's a quaint restaurant perched on a hill full of life and pasta.")
Review.create(business_id: business7.id, user_id: user9.id, rating: 5, body: "This is a great, intimate old school restaurant that great for a romantic date or catching up with friends! the service here is attentive and warm, Nancy was our server and there was a slight hiccup with our order but we didn't mind since she was so kind to us that we understood that mistakes happen! I wish i got the name of the man who constantly brought us bread and made sure our table was clean!")
Review.create(business_id: business7.id, user_id: user10.id, rating: 3, body: "I had a great time dining here but I just wish the entrees were better. The salad was okay. The dessert mediocre. I really really wanted to like this place, since it is so close to my house but atlas it was only okay.")
Review.create(business_id: business7.id, user_id: user11.id, rating: 5, body: "If you want authentic Italian food, head over to this wonderful restaurant where you are treated like family. We had a wonderful meal and evening.  If you want to get in and out, this is not the place to go.  If you want to experience a true Italian meal and spend a few relaxing hours, walk over to Trattoria Contadina.")
Review.create(business_id: business7.id, user_id: user12.id, rating: 3, body: "Don't get me wrong, I like the resturant and food. But there are a few easy things they can do better. Why would you take the plates away while one person is still eating?  It embarrasses the person still eating.  The pasta is kinda soft. Don't boil it for so long. The little things would make this place so much better.")
Review.create(business_id: business7.id, user_id: user13.id, rating: 5, body: "Went to this restaurant recently for the first time with 2 friends. The appetizers, entrees and wine were perfection. Highly recommend the gnocchi in tomato cream sauce. Service is warm and personable.")
Review.create(business_id: business7.id, user_id: user14.id, rating: 2, body: "This is the quintessential neighborhood trattoria, looks-wise. Cute as a bug. Excellent service. And the spaghetti with meatballs looked great. Unfortunately their signature pasta (which had prosciutto, sun dried tomatoes, peas, garlic, tasteless tomato cream sauce and some tubular pasta) was just awful. The special risotto was also devoid of flavor.")

Review.create(business_id: business8.id, user_id: user15.id, rating: 4, body: "Nick's is a taco stand (kinda) in a dive bar named Rouge.  This is a tough one to explain, guess you have to come here to experience it.  Regardless I'm glad we came here as lunch was wonderful.")
Review.create(business_id: business8.id, user_id: user16.id, rating: 3, body: "I came to the attached bar to watch football on Sunday... and I've been super excited to come here. But honestly, like... I just wasn't impressed. I ordered 3 tacos: fish, shrimp, and the fried chicken. So the fish was honestly delicious. The fried chicken and shrimp were both EXTREMELY dry.")
Review.create(business_id: business8.id, user_id: user17.id, rating: 4, body: "This place is a block away from my clay studio and I have become addicted to their Fish tacos. Not the grilled but the fried version, done Nick's way, is what I think about when hunger strikes. They fry one of the tortillas so it has a cup shape and the second tortilla they leave soft wrapped over the fried one and I just looooove that crunch!")
Review.create(business_id: business8.id, user_id: user18.id, rating: 2, body: "I'm husband and I can here on taco Tuesday and with as much hype as I read in these reviews, I was thoroughly disappointed for a couple of reasons. The service was horrible, and it's SO damn loud in this place on Tuesday. Probably won't be back.")
Review.create(business_id: business8.id, user_id: user19.id, rating: 5, body: "Best taco tuesdays in the city!! :) I love Nick's and the tacos are just GIGANTIC, seriously.. two is more than enough! They add a looot of meat and beans, and guac and salsa, its the perfect taco to be honest.")
Review.create(business_id: business8.id, user_id: user20.id, rating: 4, body: "Very solid for Taco Tuesday. They stuff their tacos and honestly 2 is enough for $7. The meat is a bit dry but with the sauce it balances out. the red sauce is horrid but the green one is quite delicious. We also got the chips and that was a decent deal with all the guac and accompanying veggies.")
Review.create(business_id: business8.id, user_id: user21.id, rating: 5, body: "Had an amazing time. Had a whole pitcher of margaritas at happy hour for $20! It was awesome. The street tacos were dry, but the chips were great!")

Review.create(business_id: business9.id, user_id: user1.id, rating: 4, body: "We had such a lovely evening here with out of town relatives. I thought it was a bit dressier than what others thought. I considered it to be a 'nice' restaurant not casual for those prices. Lobster thermador was amazing! So rich.")
Review.create(business_id: business9.id, user_id: user2.id, rating: 4, body: "This is one of those spots that I've heard about and was told to try, but there are so many great places to eat in SF, that I had not yet tried it...until this trip. Boy was I glad that we did. I had the Crab Thermador which was very delicious.")
Review.create(business_id: business9.id, user_id: user22.id, rating: 5, body: "Iconic SF Resturant. We enjoying coming here, staff is always friendly and knowledgeable. Food never disappoints. Not a bad seat in the house! The ambiance is part of the charm of Scoma's, it's tucked away and a little hidden but well worth going! ")
Review.create(business_id: business9.id, user_id: user23.id, rating: 5, body: "This is absolutely positively the best seafood place to eat in the wharf when you're up in San Francisco. I order the fried seafood combo scallops shrimp and fish not one bit of grease soggy seafood. They make there own house pickles. Try the poor mans. Cioppino is loaded with fresh fish clams muscles shrimping a tomato broth. The lobster bisque is the bomb. Can't wait for our next trip to Scoma's.")
Review.create(business_id: business9.id, user_id: user24.id, rating: 5, body: "This is officially my favorite restaurant in San Francisco. For years my dad raves about how good it was but I never went. And boy do I wish I had tried it earlier.")
Review.create(business_id: business9.id, user_id: user25.id, rating: 4, body: "Be sure to make reservations! I came around 5pm and was surprised how packed it was. I recommend the Dungeness crab Thermidor. It was amazing! Filled with lots of fresh crab. So hearty and very comforting. It was a little pricier than other restaurants but what do you expect since this restaurant is right on the pier.")
Review.create(business_id: business9.id, user_id: user14.id, rating: 4, body: "Came back 3rd time for lunch along with my wife. Always fantastic food ang great service. We were greeted with a smile of their staff, accommodating as always, and the food was prepared very well. The salmon and clam chowder was really delicious.")

Review.create(business_id: business10.id, user_id: user2.id, rating: 4, body: "The Boardroom was the perfect place to post up and enjoy a few hours of Football Sunday. Came to San Francisco for the first time and as much as I wanted to sight see and walk around and do this and that, Football Sunday is Football Sunday, we needed to be somewhere with a big television and crazed fans regardless of what city we were in.")
Review.create(business_id: business10.id, user_id: user7.id, rating: 5, body: "Came in on a whim from the east bay, which we rarely do. Since we were early we decided to catch the Mexico Korea World Cup soccer game. Great small neighborhood crowd. Inexpensive drinks. Pretentiousness left at the door.")
Review.create(business_id: business10.id, user_id: user5.id, rating: 5, body: "This is definitely one of my favorite sports bars in SF. The service is fantastic looking at you Justin and JP. Love y'all. But they have very good nibbles for a sports bar. I've had the tots, poutine, wings, hummus, chicken tenders, and quesadillas; all have been really tasty. Def go with the wings, I love them, Louisiana or buffalo, I like spicy. They have of course ranch or Bleu cheese as dipping sauces for the wings and bring you crema and salsa with the quesadillas.")
Review.create(business_id: business10.id, user_id: user13.id, rating: 2, body: "Not a great bar for a night cap. Bartender was rude to my friend and I. She didn't have her ID but he's never ID her then he does. But more it was his attitude. It was my birthday and he wouldn't even let her buy me a shot. She proved she was of age to.")
Review.create(business_id: business10.id, user_id: user19.id, rating: 3, body: "I was honestly going to give this place four stars--A litte far for me to come regularly, but it's a small cozy bar that is great for locals. This joint has good bar food, drinks, and snacks. However, it was brought to my attention from one of my friends that I came with that he was rudely called out by the bartender for not tipping before he even had a chance to do so. While I didn't directly experience this, I'm disappointed this happened as a first impression here.")
Review.create(business_id: business10.id, user_id: user16.id, rating: 3, body: "Came out here to watch the Warriors game last night and it was a pretty chill spot. Nothing fancy, definitely divey and small, but the crowd was chill and the staff was friendly. One big projection screen and several flat screens through out. Great selection of spirits.")
Review.create(business_id: business10.id, user_id: user17.id, rating: 5, body: "Wow. This spot came out of nowhere and really surprised me. It doesn't look like much. Looks just like another random sports bar. But when I got my bill for drinks, they were charging $2 pints and shots during happy hour. I was like this can't be right but it was.")

Review.create(business_id: business11.id, user_id: user1.id, rating: 5, body: "Mmmm this place is delicious!! The ambience is adorable and makes you feel right at home. How we, the wait here is always pretty long. We waited for about an hour on Saturday morning. Definitely recommend trying to breakfast sandwich and one of their coffee cakes!")
Review.create(business_id: business11.id, user_id: user2.id, rating: 4, body: "The service here is amazing. The staff is aware that customers wait long to be seated and they make you feel very welcome. The atmosphere is cozy. Solid brunch spot but get here early!")
Review.create(business_id: business11.id, user_id: user3.id, rating: 3, body: "My first stop when I arrived to San Francisco due to stellar reviews. I didn't have to wait 2 hours to eat like others, there was only like 3 parties ahead of us. This place is VERY tiny. You have to stand in line to order and then they seat you. The food is good don't get me wrong but the price does not reflect portions. This is literally a place to snack to hold you for like an hour before you're hungry again.")
Review.create(business_id: business11.id, user_id: user13.id, rating: 4, body: "My favorite meal is brunch so I was extremely excited to try this highly rated place when I visited SF.. The wait was pretty long, as anticipated. I think the main reason it was long was because the restaurant itself was so tiny. That being said, when you actually get inside, it goes by pretty fast. The ambiance was homey and the environment felt very similar to that of a mom and pop restaurant. I definitely would come again for the Monte Cristo though!")
Review.create(business_id: business11.id, user_id: user9.id, rating: 5, body: "Mamas is killing the breakfast game. We came on such a perfect day: scored a premium parking spot, only 30 minutes in the line, and the food came out in what felt like minutes. The server even let us sit down first, while he walked our order to the counter himself. Amazing job mamas, we'll be back for more!!!")
Review.create(business_id: business11.id, user_id: user6.id, rating: 3, body: "Good, but worth the hype? Maybe not. Like everyone says, you'll want to get their early to avoid a ridiculous wait..but even then, you're going to have to wait so bring someone you can talk to/catch up with for at least an hour if you want to not be bored out of your mind. While the food was good and typical SF prices, I feel like it's not something you HAVE to try while in SF. There's tons of brunch places in SF that don't require this long of a wait so don't feel too pressured to come here.")
Review.create(business_id: business11.id, user_id: user17.id, rating: 1, body: "In my opinion, this place is overrated and I honestly have no idea how their bathroom is not some type of health hazard! To go to the bathroom, you have to walk through the kitchen and go outside to this tiny out house (just one bathroom and it's the smallest bathroom I've ever seen). I understand they're limited on space but having customers walk through the kitchen is so weird to me. They have food sitting out and cooks doing things and I just felt so grossed out that people's hair could easily get into the food on their way to the bathroom.")

Review.create(business_id: business12.id, user_id: user4.id, rating: 1, body: "Waited 30 minutes for my smokehouse egg only to find out they completely forgot about my order. Paid around $8 for a sub par sandwich which took 40 minutes.")
Review.create(business_id: business12.id, user_id: user5.id, rating: 2, body: "I was in a rush and craving bread, so I decided that a bagel would hit the spot. Yes and no...the sesame bagel was still warm, so it was a plus that they were made fresh even at lunchtime, but it was slightly over cooked and tasted burnt. I also couldn't remember Noah's bagels being so fluffy, so I was a little disappointed about that, too, but I'm sure many other people would love them because of this. The staff were pleasant and provided quick service, so that was a plus at least.")
Review.create(business_id: business12.id, user_id: user6.id, rating: 1, body: "This store is horribly mismanaged. At 9am on a Friday, their entire case of bagels is empty. Not a single bagel in site. For a Friday in downtown San Francisco, this should be prime time to ensure you have product. As a bagel store, you have zero value with no bagels. To make matters worse, they don't even bother to acknowledge the lack of bagels in any manner until you've waited ten minutes in line, get to the front, and THEN they tell you to come back later.")
Review.create(business_id: business12.id, user_id: user14.id, rating: 3, body: "Good bagels but dirty store. Espresso machine broken. Asked for no cheese on bagel but got it anyway. Dirty rag on the floor. Probably best to do take out. Bagel was delicious.")
Review.create(business_id: business12.id, user_id: user10.id, rating: 2, body: "Came at 4 on a Tuesday. They ran out of plain bagels and only had wheat. Got two salmon bagels with cream cheese. Barely any salmon and barely any cream cheese. It's also more expensive than if you go somewhere else for the exact same bagel.")
Review.create(business_id: business12.id, user_id: user7.id, rating: 5, body: "Had an albacore tuna sandwich with side of potato salad included for 6.99. A decent lunch in financial district and it took them about 4 minutes to prepare it and it was delicious. The line was short and I will definitely go back. The only problem was they spreaded the tuna unevenly on the bagela but I was ok with it.")
Review.create(business_id: business12.id, user_id: user18.id, rating: 1, body: "Twenty minutes waiting for a bagel with cream cheese and the manager keeps taking cell calls. This is the most disorganized place I've been in a while.")

Review.create(business_id: business13.id, user_id: user15.id, rating: 5, body: "I have had this place on my go to list for a while, and I finally made it here today. Absolutely impressed with the location, view, service, and wide array of exquisite tea types and nibble options to go with it.")
Review.create(business_id: business13.id, user_id: user7.id, rating: 5, body: "Super fell in love with this restaurant. It is a content creators dream. I'm talking cute and dainty tea cups, tall glass windows, cheese boards, tea cookies. Yum! Located upstairs and overlooks a park with a pretty sweet city view.")
Review.create(business_id: business13.id, user_id: user9.id, rating: 5, body: "A wonderful place to spend the afternoon in San Francisco with delicious food and a great ambiance. The service was great and we didn't run into the issues that other people commented on. There was a slight wait before we got seating (15 min?) but that pretty much a given wherever you go in SF on the weekends. The food here was simple but delicious.")
Review.create(business_id: business13.id, user_id: user11.id, rating: 3, body: "I used to love this place - it's gorgeous and looks over the Yerba Buena Gardens. You're not paying for the food - you're paying for the ambiance. In fact, I'd never go here on my own; I only visit when I'm entertaining friends who care more about the swanky atmosphere over anything else. The price point is high, but it's convenient for both locals and tourists.")
Review.create(business_id: business13.id, user_id: user12.id, rating: 5, body: "Stopped by here for a work lunch and was very impressed. A good atmosphere and not too crowded for a work day. Our waiter was very attentive and helpful. The mochi has lots of variety, was a good texture, and flavorful.")
Review.create(business_id: business13.id, user_id: user19.id, rating: 5, body: "I LOVE being here! Eating and drinking tea outdoors is a truly divine experience in a metropolis, and the location - in the Metreon, makes it all the more majestic. Yes, I used amazing words, and this actually is that worthwhile.")

Review.create(business_id: business14.id, user_id: user1.id, rating: 4, body: "Ace Wasabi lives up to its name. The food and atmosphere are fun and lively. We made sure to arrive early for bingo time. When it was time to play, the employees went around the whole restaurant and handed out the bingo cards. Even though we didn't win a gift card, we would definitely come back.")
Review.create(business_id: business14.id, user_id: user2.id, rating: 1, body: "Overpriced for how low quality it is. Expect to pay $16-20 for any special rolls. The regular rolls are $12 and half size. Server dropped check while we were still eating (we were seated an hour from closing...)")
Review.create(business_id: business14.id, user_id: user3.id, rating: 5, body: "Snag a seat at the sushi bar and put your trust in Wilson for omakase style (chef's choice.) You won't be disappointed! Melt in your mouth toro, nigiri topped with shaved truffle, or some decadent uni.. everything is very fresh at a fair price point in comparison to high end boogie sushi spots in the city.")
Review.create(business_id: business14.id, user_id: user4.id, rating: 5, body: "With 4 nights in SF my group of girlfriends were choosy of where to eat. SO GLAD we were recommend to go to Ace! Fun lively ambiance (playlist was hip hop bbq vibes) and 5 star food. The owner Kenny is truly amazing, going above and beyond to show our group a good time.")
Review.create(business_id: business14.id, user_id: user5.id, rating: 4, body: "We had the seasonal 20 piece sashimi which came out fast and was super filling. I highly recommend the Hamachi Kama ($7), the grilled yellowtail collar with ponzu which was such a steal. Ace Wasabi has a fun bingo activity that happens at the end of HH if you can stick around. Fun vibes, good deals, what more can you ask for?")
Review.create(business_id: business14.id, user_id: user6.id, rating: 4, body: "Fun vibe, fusion sushi. They have a great HH menu, including sashimi platters, rolls, small plates and bottles of wine for half off. Really good deal, especially in the Marina!")

Review.create(business_id: business15.id, user_id: user7.id, rating: 5, body: "Contemporary decor with lovely umami finesse in their sake that they recommended! Fresh nigiri and amaebi, shrimp, was sweet that one can taste!  Uni was amicable as well as the other nigiri that was ordered up!  Mackerel must get!")
Review.create(business_id: business15.id, user_id: user8.id, rating: 4, body: "Late post: family QT. This place is pretty good and they cater to kids too. The only issue was the food took a while and the waiter miss one order which we didn't even order much. Overall service was ok. I did notice he was the only server so prob short staff. Overall I enjoyed it and would come again.")
Review.create(business_id: business15.id, user_id: user9.id, rating: 5, body: "Love this new hotspot! Came here when they first opened. My cousin brought me here before my surprise birthday party and it was so much fun. The staff here are so stylish! Total trendy Tokyo vibes. We went all out on sushi and sake.")
Review.create(business_id: business15.id, user_id: user10.id, rating: 5, body: "We sat at the bar and really appreciated how the chefs and waiters would recommend particular types of nigiri to try. If you like stronger tasting fish (e.g. mackerel) I highly recommend the butterfish!")
Review.create(business_id: business15.id, user_id: user11.id, rating: 4, body: "Been wanting to try for a while and finally walked by today and decided to drop in for lunch. Even on the weekend, they still offered the lunch specials so I opted for the Deluxe Chirashi. The chef was super nice and service was fast.")
Review.create(business_id: business15.id, user_id: user12.id, rating: 5, body: "We ordered the nigiri tasting this time. Every piece was fresh and tasty. Half baked rolls were very yummy. I love the sweet potatoes inside. We also ordered the chawanmushi which contains egg, cheese, and mushrooms. Very delicious and well presented.")

Review.create(business_id: business16.id, user_id: user14.id, rating: 4, body: "No nonsense dim sum spot in Chinatown. After waiting in a short line outside, you order at the counter and they bag up your food for you. There isn't any seating inside, so expect to take the food to go. Definitely a hectic experience, but nothing out of the ordinary.")
Review.create(business_id: business16.id, user_id: user15.id, rating: 5, body: "This hole-in-the-wall does accept credit cards but most people still pay with cash, and I'd recommend it as well. You may be given a look if you try to pay with card, but I appreciate that they try by accepting cards.")
Review.create(business_id: business16.id, user_id: user16.id, rating: 5, body: "If you want authentic Chinese pastries at cheap prices then this is the best spot in SF Chinatown.  It doesn't look aesthetically appealing on the outside but the food is worth it.  I believe they accept cards based on the signage.  But, I would bring cash to these Asian hole in the wall bakeries to be on the safe side.")
Review.create(business_id: business16.id, user_id: user17.id, rating: 5, body: "This little bakery is a Chinatown staple. Yes, there's literally always a line but for good reason. The dim sum is pretty quality, especially for the price, and the perfect spot if you're just craving some xia jiao (shrimp dumplings) for a quick lunch. The prices here are unreal. We're talking $2.50 for 3 pieces of dim sum in San Francisco.")
Review.create(business_id: business16.id, user_id: user18.id, rating: 5, body: "I really like the shrimp dumplings cause they're so shrimpy, and the har gow is really big and filling too.  Sometimes I see new things I've never tried before and they don't judge when I have to point to pick. Cash or credit is okay. I'll definitely be back!")
Review.create(business_id: business16.id, user_id: user19.id, rating: 5, body: "Good Mong Kok is my favorite spot in SF's Chinatown.  The lines aren't really that bad, I think I waited around 15 minutes on a Saturday morning.   What makes their dimsum so delicious?  Probably the fact that the old ladies in there don't speak a whole lot of English, the dumplings are made fresh fresh fresh, and because these dimsums don't require me to drench them in soy sauce and hot pepper.")


cat1 = Category.create(name: "Breakfast")
cat2 = Category.create(name: "Lunch")
cat3 = Category.create(name: "Dinner")
cat4 = Category.create(name: "Seafood")
cat5 = Category.create(name: "Asian")
cat6 = Category.create(name: "Asian Fusion")
cat7 = Category.create(name: "Mexican")
cat8 = Category.create(name: "Italian")
cat9 = Category.create(name: "American")


BusinessCategory.create(business_id: business1.id, category_id: cat3.id)
BusinessCategory.create(business_id: business1.id, category_id: cat4.id)
BusinessCategory.create(business_id: business2.id, category_id: cat3.id)
BusinessCategory.create(business_id: business2.id, category_id: cat5.id)
BusinessCategory.create(business_id: business3.id, category_id: cat3.id)
BusinessCategory.create(business_id: business3.id, category_id: cat6.id)
BusinessCategory.create(business_id: business4.id, category_id: cat3.id)
BusinessCategory.create(business_id: business4.id, category_id: cat4.id)
BusinessCategory.create(business_id: business5.id, category_id: cat3.id)
BusinessCategory.create(business_id: business5.id, category_id: cat9.id)
BusinessCategory.create(business_id: business6.id, category_id: cat2.id)
BusinessCategory.create(business_id: business6.id, category_id: cat7.id)
BusinessCategory.create(business_id: business7.id, category_id: cat3.id)
BusinessCategory.create(business_id: business7.id, category_id: cat8.id)
BusinessCategory.create(business_id: business8.id, category_id: cat2.id)
BusinessCategory.create(business_id: business8.id, category_id: cat7.id)
BusinessCategory.create(business_id: business9.id, category_id: cat2.id)
BusinessCategory.create(business_id: business9.id, category_id: cat4.id)
BusinessCategory.create(business_id: business10.id, category_id: cat2.id)
BusinessCategory.create(business_id: business10.id, category_id: cat9.id)
BusinessCategory.create(business_id: business11.id, category_id: cat1.id)
BusinessCategory.create(business_id: business11.id, category_id: cat9.id)
BusinessCategory.create(business_id: business12.id, category_id: cat1.id)
BusinessCategory.create(business_id: business12.id, category_id: cat9.id)
BusinessCategory.create(business_id: business13.id, category_id: cat1.id)
BusinessCategory.create(business_id: business13.id, category_id: cat5.id)
BusinessCategory.create(business_id: business14.id, category_id: cat2.id)
BusinessCategory.create(business_id: business14.id, category_id: cat4.id)
BusinessCategory.create(business_id: business15.id, category_id: cat3.id)
BusinessCategory.create(business_id: business15.id, category_id: cat4.id)
BusinessCategory.create(business_id: business16.id, category_id: cat1.id)
BusinessCategory.create(business_id: business16.id, category_id: cat5.id)